FROM node:11.10

WORKDIR '/app'
COPY ./package.json ./yarn.lock ./
RUN apt-get update \
            && apt-get install -y node-gyp
RUN yarn global add @angular/cli
RUN yarn
COPY ./ ./
EXPOSE 4200
CMD ["yarn", "hmr"]
