const req = {
    _readableState:
        ReadableState {
        objectMode: false,
            highWaterMark: 16384,
            buffer: BufferList { head: null, tail: null, length: 0 },
        length: 0,
            pipes: null,
            pipesCount: 0,
            flowing: true,
            ended: true,
            endEmitted: true,
            reading: false,
            sync: false,
            needReadable: false,
            emittedReadable: false,
            readableListening: false,
            resumeScheduled: false,
            paused: false,
            emitClose: true,
            destroyed: false,
            defaultEncoding: 'utf8',
            awaitDrain: 0,
            readingMore: false,
            decoder: null,
            encoding: null },
    readable: false,
        _events: [Object: null prototype] {},
    _eventsCount: 0,
        _maxListeners: undefined,
        socket:
    Socket {
        connecting: false,
            _hadError: false,
            _handle:
        TCP {
            reading: true,
                onread: [Function: onStreamRead],
            onconnection: null,
                _consumed: true,
                [Symbol(owner)]: [Circular] },
        _parent: null,
            _host: null,
            _readableState:
        ReadableState {
            objectMode: false,
                highWaterMark: 16384,
                buffer: BufferList { head: null, tail: null, length: 0 },
            length: 0,
                pipes: null,
                pipesCount: 0,
                flowing: true,
                ended: false,
                endEmitted: false,
                reading: true,
                sync: false,
                needReadable: true,
                emittedReadable: false,
                readableListening: false,
                resumeScheduled: false,
                paused: false,
                emitClose: false,
                destroyed: false,
                defaultEncoding: 'utf8',
                awaitDrain: 0,
                readingMore: false,
                decoder: null,
                encoding: null },
        readable: true,
            _events:
        [Object: null prototype] {
            end: [Array],
                drain: [Array],
                timeout: [Function: socketOnTimeout],
            data: [Function: bound socketOnData],
            error: [Array],
                close: [Array],
                resume: [Function: onSocketResume],
            pause: [Function: onSocketPause] },
        _eventsCount: 8,
            _maxListeners: undefined,
            _writableState:
        WritableState {
            objectMode: false,
                highWaterMark: 16384,
                finalCalled: false,
                needDrain: false,
                ending: false,
                ended: false,
                finished: false,
                destroyed: false,
                decodeStrings: false,
                defaultEncoding: 'utf8',
                length: 0,
                writing: false,
                corked: 0,
                sync: true,
                bufferProcessing: false,
                onwrite: [Function: bound onwrite],
            writecb: null,
                writelen: 0,
                bufferedRequest: null,
                lastBufferedRequest: null,
                pendingcb: 0,
                prefinished: false,
                errorEmitted: false,
                emitClose: false,
                bufferedRequestCount: 0,
                corkedRequestsFree: [Object] },
        writable: true,
            allowHalfOpen: true,
            _sockname: null,
            _pendingData: null,
            _pendingEncoding: '',
            server:
        Server {
            _events: [Object],
                _eventsCount: 5,
                _maxListeners: undefined,
                _connections: 3,
                _handle: [TCP],
                _usingWorkers: false,
                _workers: [],
                _unref: false,
                allowHalfOpen: true,
                pauseOnConnect: false,
                httpAllowHalfOpen: false,
                timeout: 120000,
                keepAliveTimeout: 5000,
                _pendingResponseData: 0,
                maxHeadersCount: null,
                headersTimeout: 40000,
                _connectionKey: '6::::3000',
                [Symbol(IncomingMessage)]: [Function],
                [Symbol(ServerResponse)]: [Function],
                [Symbol(asyncId)]: 25 },
        _server:
            Server {
            _events: [Object],
                _eventsCount: 5,
                _maxListeners: undefined,
                _connections: 3,
                _handle: [TCP],
                _usingWorkers: false,
                _workers: [],
                _unref: false,
                allowHalfOpen: true,
                pauseOnConnect: false,
                httpAllowHalfOpen: false,
                timeout: 120000,
                keepAliveTimeout: 5000,
                _pendingResponseData: 0,
                maxHeadersCount: null,
                headersTimeout: 40000,
                _connectionKey: '6::::3000',
                [Symbol(IncomingMessage)]: [Function],
                [Symbol(ServerResponse)]: [Function],
                [Symbol(asyncId)]: 25 },
        timeout: 120000,
            parser:
        HTTPParser {
            '0': [Function: parserOnHeaders],
            '1': [Function: parserOnHeadersComplete],
            '2': [Function: parserOnBody],
            '3': [Function: parserOnMessageComplete],
            '4': [Function: bound onParserExecute],
            _headers: [],
                _url: '',
                socket: [Circular],
                incoming: [Circular],
                outgoing: null,
                maxHeaderPairs: 2000,
                _consumed: true,
                onIncoming: [Function: bound parserOnIncoming],
            parsingHeadersStart: 0,
                [Symbol(isReused)]: true },
        on: [Function: socketOnWrap],
        _paused: false,
            _httpMessage:
        ServerResponse {
            _events: [Object],
                _eventsCount: 2,
                _maxListeners: undefined,
                output: [],
                outputEncodings: [],
                outputCallbacks: [],
                outputSize: 0,
                writable: true,
                _last: false,
                chunkedEncoding: false,
                shouldKeepAlive: false,
                useChunkedEncodingByDefault: true,
                sendDate: true,
                _removedConnection: false,
                _removedContLen: false,
                _removedTE: false,
                _contentLength: null,
                _hasBody: true,
                _trailer: '',
                finished: false,
                _headerSent: false,
                socket: [Circular],
                connection: [Circular],
                _header: null,
                _onPendingData: [Function: bound updateOutgoingData],
            _sent100: false,
                _expect_continue: false,
                req: [Circular],
                locals: [Object: null prototype] {},
            _startAt: undefined,
                _startTime: undefined,
                writeHead: [Function: writeHead],
            __onFinished: [Function],
                [Symbol(isCorked)]: false,
                [Symbol(outHeadersKey)]: [Object] },
        _peername: { address: '::1', family: 'IPv6', port: 53448 },
        [Symbol(asyncId)]: 269,
            [Symbol(lastWriteQueueSize)]: 0,
            [Symbol(timeout)]:
        Timeout {
            _called: false,
                _idleTimeout: 120000,
                _idlePrev: [TimersList],
                _idleNext: [TimersList],
                _idleStart: 45206,
                _onTimeout: [Function: bound ],
            _timerArgs: undefined,
                _repeat: null,
                _destroyed: false,
                [Symbol(unrefed)]: true,
                [Symbol(asyncId)]: 270,
                [Symbol(triggerId)]: 269 },
        [Symbol(kBytesRead)]: 0,
            [Symbol(kBytesWritten)]: 0 },
    connection:
        Socket {
        connecting: false,
            _hadError: false,
            _handle:
        TCP {
            reading: true,
                onread: [Function: onStreamRead],
            onconnection: null,
                _consumed: true,
                [Symbol(owner)]: [Circular] },
        _parent: null,
            _host: null,
            _readableState:
        ReadableState {
            objectMode: false,
                highWaterMark: 16384,
                buffer: BufferList { head: null, tail: null, length: 0 },
            length: 0,
                pipes: null,
                pipesCount: 0,
                flowing: true,
                ended: false,
                endEmitted: false,
                reading: true,
                sync: false,
                needReadable: true,
                emittedReadable: false,
                readableListening: false,
                resumeScheduled: false,
                paused: false,
                emitClose: false,
                destroyed: false,
                defaultEncoding: 'utf8',
                awaitDrain: 0,
                readingMore: false,
                decoder: null,
                encoding: null },
        readable: true,
            _events:
        [Object: null prototype] {
            end: [Array],
                drain: [Array],
                timeout: [Function: socketOnTimeout],
            data: [Function: bound socketOnData],
            error: [Array],
                close: [Array],
                resume: [Function: onSocketResume],
            pause: [Function: onSocketPause] },
        _eventsCount: 8,
            _maxListeners: undefined,
            _writableState:
        WritableState {
            objectMode: false,
                highWaterMark: 16384,
                finalCalled: false,
                needDrain: false,
                ending: false,
                ended: false,
                finished: false,
                destroyed: false,
                decodeStrings: false,
                defaultEncoding: 'utf8',
                length: 0,
                writing: false,
                corked: 0,
                sync: true,
                bufferProcessing: false,
                onwrite: [Function: bound onwrite],
            writecb: null,
                writelen: 0,
                bufferedRequest: null,
                lastBufferedRequest: null,
                pendingcb: 0,
                prefinished: false,
                errorEmitted: false,
                emitClose: false,
                bufferedRequestCount: 0,
                corkedRequestsFree: [Object] },
        writable: true,
            allowHalfOpen: true,
            _sockname: null,
            _pendingData: null,
            _pendingEncoding: '',
            server:
        Server {
            _events: [Object],
                _eventsCount: 5,
                _maxListeners: undefined,
                _connections: 3,
                _handle: [TCP],
                _usingWorkers: false,
                _workers: [],
                _unref: false,
                allowHalfOpen: true,
                pauseOnConnect: false,
                httpAllowHalfOpen: false,
                timeout: 120000,
                keepAliveTimeout: 5000,
                _pendingResponseData: 0,
                maxHeadersCount: null,
                headersTimeout: 40000,
                _connectionKey: '6::::3000',
                [Symbol(IncomingMessage)]: [Function],
                [Symbol(ServerResponse)]: [Function],
                [Symbol(asyncId)]: 25 },
        _server:
            Server {
            _events: [Object],
                _eventsCount: 5,
                _maxListeners: undefined,
                _connections: 3,
                _handle: [TCP],
                _usingWorkers: false,
                _workers: [],
                _unref: false,
                allowHalfOpen: true,
                pauseOnConnect: false,
                httpAllowHalfOpen: false,
                timeout: 120000,
                keepAliveTimeout: 5000,
                _pendingResponseData: 0,
                maxHeadersCount: null,
                headersTimeout: 40000,
                _connectionKey: '6::::3000',
                [Symbol(IncomingMessage)]: [Function],
                [Symbol(ServerResponse)]: [Function],
                [Symbol(asyncId)]: 25 },
        timeout: 120000,
            parser:
        HTTPParser {
            '0': [Function: parserOnHeaders],
            '1': [Function: parserOnHeadersComplete],
            '2': [Function: parserOnBody],
            '3': [Function: parserOnMessageComplete],
            '4': [Function: bound onParserExecute],
            _headers: [],
                _url: '',
                socket: [Circular],
                incoming: [Circular],
                outgoing: null,
                maxHeaderPairs: 2000,
                _consumed: true,
                onIncoming: [Function: bound parserOnIncoming],
            parsingHeadersStart: 0,
                [Symbol(isReused)]: true },
        on: [Function: socketOnWrap],
        _paused: false,
            _httpMessage:
        ServerResponse {
            _events: [Object],
                _eventsCount: 2,
                _maxListeners: undefined,
                output: [],
                outputEncodings: [],
                outputCallbacks: [],
                outputSize: 0,
                writable: true,
                _last: false,
                chunkedEncoding: false,
                shouldKeepAlive: false,
                useChunkedEncodingByDefault: true,
                sendDate: true,
                _removedConnection: false,
                _removedContLen: false,
                _removedTE: false,
                _contentLength: null,
                _hasBody: true,
                _trailer: '',
                finished: false,
                _headerSent: false,
                socket: [Circular],
                connection: [Circular],
                _header: null,
                _onPendingData: [Function: bound updateOutgoingData],
            _sent100: false,
                _expect_continue: false,
                req: [Circular],
                locals: [Object: null prototype] {},
            _startAt: undefined,
                _startTime: undefined,
                writeHead: [Function: writeHead],
            __onFinished: [Function],
                [Symbol(isCorked)]: false,
                [Symbol(outHeadersKey)]: [Object] },
        _peername: { address: '::1', family: 'IPv6', port: 53448 },
        [Symbol(asyncId)]: 269,
            [Symbol(lastWriteQueueSize)]: 0,
            [Symbol(timeout)]:
        Timeout {
            _called: false,
                _idleTimeout: 120000,
                _idlePrev: [TimersList],
                _idleNext: [TimersList],
                _idleStart: 45206,
                _onTimeout: [Function: bound ],
            _timerArgs: undefined,
                _repeat: null,
                _destroyed: false,
                [Symbol(unrefed)]: true,
                [Symbol(asyncId)]: 270,
                [Symbol(triggerId)]: 269 },
        [Symbol(kBytesRead)]: 0,
            [Symbol(kBytesWritten)]: 0 },
    httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers:
    { host: '20a7e2d1.ngrok.io',
        'user-agent': 'Stripe/1.0 (+https://stripe.com/docs/webhooks)',
        connection: 'close',
        'content-length': '3162',
        accept: '*/*; q=0.5, application/xml',
        'cache-control': 'no-cache',
        'content-type': 'application/json; charset=utf-8',
        'stripe-signature':
        't=1548953711,v1=2f43ee40b45fa1d7c7f73cb2a4e768ccb59e5b0a28028716ac8bf913dee50192,v0=379b9559dc9fdeb83fc058407f3ff116aa9c0343660c2e54c2bdc9b9c0246b3d',
            'x-forwarded-for': '54.187.174.169' },
    rawHeaders:
        [ 'Host',
            '20a7e2d1.ngrok.io',
            'User-Agent',
            'Stripe/1.0 (+https://stripe.com/docs/webhooks)',
            'Connection',
            'close',
            'Content-Length',
            '3162',
            'Accept',
            '*/*; q=0.5, application/xml',
            'Cache-Control',
            'no-cache',
            'Content-Type',
            'application/json; charset=utf-8',
            'Stripe-Signature',
            't=1548953711,v1=2f43ee40b45fa1d7c7f73cb2a4e768ccb59e5b0a28028716ac8bf913dee50192,v0=379b9559dc9fdeb83fc058407f3ff116aa9c0343660c2e54c2bdc9b9c0246b3d',
            'X-Forwarded-For',
            '54.187.174.169' ],
            trailers: {},
    rawTrailers: [],
        aborted: false,
        upgrade: false,
        url: '/paymentSuccessful',
        method: 'POST',
        statusCode: null,
        statusMessage: null,
        client:
    Socket {
        connecting: false,
            _hadError: false,
            _handle:
        TCP {
            reading: true,
                onread: [Function: onStreamRead],
            onconnection: null,
                _consumed: true,
                [Symbol(owner)]: [Circular] },
        _parent: null,
            _host: null,
            _readableState:
        ReadableState {
            objectMode: false,
                highWaterMark: 16384,
                buffer: BufferList { head: null, tail: null, length: 0 },
            length: 0,
                pipes: null,
                pipesCount: 0,
                flowing: true,
                ended: false,
                endEmitted: false,
                reading: true,
                sync: false,
                needReadable: true,
                emittedReadable: false,
                readableListening: false,
                resumeScheduled: false,
                paused: false,
                emitClose: false,
                destroyed: false,
                defaultEncoding: 'utf8',
                awaitDrain: 0,
                readingMore: false,
                decoder: null,
                encoding: null },
        readable: true,
            _events:
        [Object: null prototype] {
            end: [Array],
                drain: [Array],
                timeout: [Function: socketOnTimeout],
            data: [Function: bound socketOnData],
            error: [Array],
                close: [Array],
                resume: [Function: onSocketResume],
            pause: [Function: onSocketPause] },
        _eventsCount: 8,
            _maxListeners: undefined,
            _writableState:
        WritableState {
            objectMode: false,
                highWaterMark: 16384,
                finalCalled: false,
                needDrain: false,
                ending: false,
                ended: false,
                finished: false,
                destroyed: false,
                decodeStrings: false,
                defaultEncoding: 'utf8',
                length: 0,
                writing: false,
                corked: 0,
                sync: true,
                bufferProcessing: false,
                onwrite: [Function: bound onwrite],
            writecb: null,
                writelen: 0,
                bufferedRequest: null,
                lastBufferedRequest: null,
                pendingcb: 0,
                prefinished: false,
                errorEmitted: false,
                emitClose: false,
                bufferedRequestCount: 0,
                corkedRequestsFree: [Object] },
        writable: true,
            allowHalfOpen: true,
            _sockname: null,
            _pendingData: null,
            _pendingEncoding: '',
            server:
        Server {
            _events: [Object],
                _eventsCount: 5,
                _maxListeners: undefined,
                _connections: 3,
                _handle: [TCP],
                _usingWorkers: false,
                _workers: [],
                _unref: false,
                allowHalfOpen: true,
                pauseOnConnect: false,
                httpAllowHalfOpen: false,
                timeout: 120000,
                keepAliveTimeout: 5000,
                _pendingResponseData: 0,
                maxHeadersCount: null,
                headersTimeout: 40000,
                _connectionKey: '6::::3000',
                [Symbol(IncomingMessage)]: [Function],
                [Symbol(ServerResponse)]: [Function],
                [Symbol(asyncId)]: 25 },
        _server:
            Server {
            _events: [Object],
                _eventsCount: 5,
                _maxListeners: undefined,
                _connections: 3,
                _handle: [TCP],
                _usingWorkers: false,
                _workers: [],
                _unref: false,
                allowHalfOpen: true,
                pauseOnConnect: false,
                httpAllowHalfOpen: false,
                timeout: 120000,
                keepAliveTimeout: 5000,
                _pendingResponseData: 0,
                maxHeadersCount: null,
                headersTimeout: 40000,
                _connectionKey: '6::::3000',
                [Symbol(IncomingMessage)]: [Function],
                [Symbol(ServerResponse)]: [Function],
                [Symbol(asyncId)]: 25 },
        timeout: 120000,
            parser:
        HTTPParser {
            '0': [Function: parserOnHeaders],
            '1': [Function: parserOnHeadersComplete],
            '2': [Function: parserOnBody],
            '3': [Function: parserOnMessageComplete],
            '4': [Function: bound onParserExecute],
            _headers: [],
                _url: '',
                socket: [Circular],
                incoming: [Circular],
                outgoing: null,
                maxHeaderPairs: 2000,
                _consumed: true,
                onIncoming: [Function: bound parserOnIncoming],
            parsingHeadersStart: 0,
                [Symbol(isReused)]: true },
        on: [Function: socketOnWrap],
        _paused: false,
            _httpMessage:
        ServerResponse {
            _events: [Object],
                _eventsCount: 2,
                _maxListeners: undefined,
                output: [],
                outputEncodings: [],
                outputCallbacks: [],
                outputSize: 0,
                writable: true,
                _last: false,
                chunkedEncoding: false,
                shouldKeepAlive: false,
                useChunkedEncodingByDefault: true,
                sendDate: true,
                _removedConnection: false,
                _removedContLen: false,
                _removedTE: false,
                _contentLength: null,
                _hasBody: true,
                _trailer: '',
                finished: false,
                _headerSent: false,
                socket: [Circular],
                connection: [Circular],
                _header: null,
                _onPendingData: [Function: bound updateOutgoingData],
            _sent100: false,
                _expect_continue: false,
                req: [Circular],
                locals: [Object: null prototype] {},
            _startAt: undefined,
                _startTime: undefined,
                writeHead: [Function: writeHead],
            __onFinished: [Function],
                [Symbol(isCorked)]: false,
                [Symbol(outHeadersKey)]: [Object] },
        _peername: { address: '::1', family: 'IPv6', port: 53448 },
        [Symbol(asyncId)]: 269,
            [Symbol(lastWriteQueueSize)]: 0,
            [Symbol(timeout)]:
        Timeout {
            _called: false,
                _idleTimeout: 120000,
                _idlePrev: [TimersList],
                _idleNext: [TimersList],
                _idleStart: 45206,
                _onTimeout: [Function: bound ],
            _timerArgs: undefined,
                _repeat: null,
                _destroyed: false,
                [Symbol(unrefed)]: true,
                [Symbol(asyncId)]: 270,
                [Symbol(triggerId)]: 269 },
        [Symbol(kBytesRead)]: 0,
            [Symbol(kBytesWritten)]: 0 },
    _consuming: true,
        _dumped: false,
        next: [Function: next],
    baseUrl: '/api/webhooks',
        originalUrl: '/api/webhooks/paymentSuccessful',
        _parsedUrl:
    Url {
        protocol: null,
            slashes: null,
            auth: null,
            host: null,
            port: null,
            hostname: null,
            hash: null,
            search: null,
            query: null,
            pathname: '/paymentSuccessful',
            path: '/paymentSuccessful',
            href: '/paymentSuccessful',
            _raw: '/paymentSuccessful' },
    params: {},
    query: {},
    res:
        ServerResponse {
        _events:
            [Object: null prototype] { finish: [Array], end: [Function: onevent] },
        _eventsCount: 2,
            _maxListeners: undefined,
            output: [],
            outputEncodings: [],
            outputCallbacks: [],
            outputSize: 0,
            writable: true,
            _last: false,
            chunkedEncoding: false,
            shouldKeepAlive: false,
            useChunkedEncodingByDefault: true,
            sendDate: true,
            _removedConnection: false,
            _removedContLen: false,
            _removedTE: false,
            _contentLength: null,
            _hasBody: true,
            _trailer: '',
            finished: false,
            _headerSent: false,
            socket:
        Socket {
            connecting: false,
                _hadError: false,
                _handle: [TCP],
                _parent: null,
                _host: null,
                _readableState: [ReadableState],
                readable: true,
                _events: [Object],
                _eventsCount: 8,
                _maxListeners: undefined,
                _writableState: [WritableState],
                writable: true,
                allowHalfOpen: true,
                _sockname: null,
                _pendingData: null,
                _pendingEncoding: '',
                server: [Server],
                _server: [Server],
                timeout: 120000,
                parser: [HTTPParser],
                on: [Function: socketOnWrap],
            _paused: false,
                _httpMessage: [Circular],
                _peername: [Object],
                [Symbol(asyncId)]: 269,
                [Symbol(lastWriteQueueSize)]: 0,
                [Symbol(timeout)]:
            Timeout {
                _called: false,
                    _idleTimeout: 120000,
                    _idlePrev: [TimersList],
                    _idleNext: [TimersList],
                    _idleStart: 45206,
                    _onTimeout: [Function: bound ],
                _timerArgs: undefined,
                    _repeat: null,
                    _destroyed: false,
                    [Symbol(unrefed)]: true,
                    [Symbol(asyncId)]: 270,
                    [Symbol(triggerId)]: 269 },
            [Symbol(kBytesRead)]: 0,
                [Symbol(kBytesWritten)]: 0 },
        connection:
            Socket {
            connecting: false,
                _hadError: false,
                _handle: [TCP],
                _parent: null,
                _host: null,
                _readableState: [ReadableState],
                readable: true,
                _events: [Object],
                _eventsCount: 8,
                _maxListeners: undefined,
                _writableState: [WritableState],
                writable: true,
                allowHalfOpen: true,
                _sockname: null,
                _pendingData: null,
                _pendingEncoding: '',
                server: [Server],
                _server: [Server],
                timeout: 120000,
                parser: [HTTPParser],
                on: [Function: socketOnWrap],
            _paused: false,
                _httpMessage: [Circular],
                _peername: [Object],
                [Symbol(asyncId)]: 269,
                [Symbol(lastWriteQueueSize)]: 0,
                [Symbol(timeout)]:
            Timeout {
                _called: false,
                    _idleTimeout: 120000,
                    _idlePrev: [TimersList],
                    _idleNext: [TimersList],
                    _idleStart: 45206,
                    _onTimeout: [Function: bound ],
                _timerArgs: undefined,
                    _repeat: null,
                    _destroyed: false,
                    [Symbol(unrefed)]: true,
                    [Symbol(asyncId)]: 270,
                    [Symbol(triggerId)]: 269 },
            [Symbol(kBytesRead)]: 0,
                [Symbol(kBytesWritten)]: 0 },
        _header: null,
            _onPendingData: [Function: bound updateOutgoingData],
        _sent100: false,
            _expect_continue: false,
            req: [Circular],
            locals: [Object: null prototype] {},
        _startAt: undefined,
            _startTime: undefined,
            writeHead: [Function: writeHead],
        __onFinished: { [Function: listener] queue: [Array] },
        [Symbol(isCorked)]: false,
            [Symbol(outHeadersKey)]:
        [Object: null prototype] {
            'x-powered-by': [Array],
                'access-control-allow-origin': [Array] } },
    body:
    { created: 1326853478,
        livemode: false,
        id: 'invoice.payment_00000000000000',
        type: 'invoice.payment_succeeded',
        object: 'event',
        request: null,
        pending_webhooks: 1,
        api_version: '2018-11-08',
        data: { object: [Object] } },
    _body: true,
        length: undefined,
        _startAt: [ 12495, 659809042 ],
        _startTime: 2019-01-31T16:55:11.681Z,
        _remoteAddress: '::1',
        route:
    Route {
        path: '/paymentSuccessful',
            stack: [ [Layer] ],
            methods: { post: true } } }

