version: '3.6'

services:

  mongodb:
    image: 'mongo:latest'
    ports:
      - 27017:27017
    # networks:
    #   - backend
    volumes:
      - data_db:/data/db
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
  
  redis:
    image: 'redis:latest'
    # networks:
    #   - backend
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  
  api:
    image: 'octoniusapp/octonius:api'
    # networks:
    #   - backend
    volumes:
      - data_uploads:/app/uploads # mount uploads folder inside container's app folder
    environment:
      - PORT=3000
      - dbURL=mongodb://mongodb:27017/octonius
      - JWT_KEY=asfsaf12safas23fsafa12sf
      - SENDGRID_KEY=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
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SK_STRIPE=sk_test_dvebbZQPA4Vk8kKZaEuN32sD
      - stripe_plan=plan_EK1uRUJLJcDS6e
      - WEBHOOK_PS_SECRET=whsec_pmcLdxoYxBAdZswT2ZzWYep2WmnBW8Sn
    depends_on:
      - mongodb
      - redis
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
  
  client:
    image: 'octoniusapp/octonius:client'
    # networks:
    #   - frontend
    depends_on:
      - api
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  
  nginx:
    image: 'octoniusapp/octonius:nginx'
    # networks:
    #   - frontend
    #   - backend
    ports:
      - 3000:80
    depends_on:
      - api
      - client
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
    

volumes:

  data_db:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/db
      o: bind

  data_uploads:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/uploads
      o: bind

# networks:
#   frontend: {}
#   backend: {} 
