import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Injectable({
  providedIn: 'root'
})
export class CountryCurrencyService {

  currencies = [
    { code: 'AFN', name: $localize`:@@countrycurrencyservice.afn:Afghanistan Afghanis - AFN`},
    { code: 'ALL', name: $localize`:@@countrycurrencyservice.all:Albania Leke - ALL`},
    { code: 'DZD', name: $localize`:@@countrycurrencyservice.dzd:Algeria Dinars - DZD`},
    { code: 'ARS', name: $localize`:@@countrycurrencyservice.ars:Argentina Pesos - ARS`},
    { code: 'AUD', name: $localize`:@@countrycurrencyservice.aud:Australia Dollars - AUD`},
    { code: 'BSD', name: $localize`:@@countrycurrencyservice.bsd:Bahamas Dollars - BSD`},
    { code: 'BHD', name: $localize`:@@countrycurrencyservice.bhd:Bahrain Dinars - BHD`},
    { code: 'BDT', name: $localize`:@@countrycurrencyservice.bdt:Bangladesh Taka - BDT`},
    { code: 'BBD', name: $localize`:@@countrycurrencyservice.bbd:Barbados Dollars - BBD`},
    { code: 'BMD', name: $localize`:@@countrycurrencyservice.bmd:Bermuda Dollars - BMD`},
    { code: 'BRL', name: $localize`:@@countrycurrencyservice.brl:Brazil Reais - BRL`},
    { code: 'CAD', name: $localize`:@@countrycurrencyservice.cad:Canada Dollars - CAD`},
    { code: 'XOF', name: $localize`:@@countrycurrencyservice.xof:CFA BCEAO Francs - XOF`},
    { code: 'XAF', name: $localize`:@@countrycurrencyservice.xaf:CFA BEAC Francs - XAF`},
    { code: 'CLP', name: $localize`:@@countrycurrencyservice.clp:Chile Pesos - CLP`},
    { code: 'CNY', name: $localize`:@@countrycurrencyservice.cny:China Yuan Renminbi - CNY`},
    { code: 'COP', name: $localize`:@@countrycurrencyservice.cop:Colombia Pesos - COP`},
    { code: 'XPF', name: $localize`:@@countrycurrencyservice.xpf:CFP Francs - XPF`},
    { code: 'CRC', name: $localize`:@@countrycurrencyservice.crc:Costa Rica Colones - CRC`},
    { code: 'CYP', name: $localize`:@@countrycurrencyservice.cyp:Cyprus Pounds - CYP`},
    { code: 'DOP', name: $localize`:@@countrycurrencyservice.dop:Dominican Republic Pesos - DOP`},
    { code: 'XCD', name: $localize`:@@countrycurrencyservice.xcd:Eastern Caribbean Dollars - XCD`},
    { code: 'EGP', name: $localize`:@@countrycurrencyservice.egp:Egypt Pounds - EGP`},
    { code: 'EEK', name: $localize`:@@countrycurrencyservice.eek:Estonia Krooni - EEK`},
    { code: 'EUR', name: $localize`:@@countryCurrencyService.eur:Euro - EUR`},
    { code: 'FJD', name: $localize`:@@countrycurrencyservice.fjd:Fiji Dollars - FJD`},
    { code: 'FIM', name: $localize`:@@countrycurrencyservice.fim:Finland Markkaa - FIM`},
    { code: 'XAU', name: $localize`:@@countrycurrencyservice.xau:Gold Ounces - XAU`},
    { code: 'GTQ', name: $localize`:@@countrycurrencyservice.gtq:Guatemalan Quetzal - GTQ`},
    { code: 'HKD', name: $localize`:@@countrycurrencyservice.hkd:Hong Kong Dollars - HKD`},
    { code: 'HUF', name: $localize`:@@countrycurrencyservice.huf:Hungary Forint - HUF`},
    { code: 'ISK', name: $localize`:@@countrycurrencyservice.isk:Iceland Kronur - ISK`},
    { code: 'XDR', name: $localize`:@@countrycurrencyservice.xdr:IMF Special Drawing Right - XDR`},
    { code: 'INR', name: $localize`:@@countrycurrencyservice.inr:India Rupees - INR`},
    { code: 'IDR', name: $localize`:@@countrycurrencyservice.idr:Indonesia Rupiahs - IDR`},
    { code: 'IRR', name: $localize`:@@countrycurrencyservice.irr:Iran Rials - IRR`},
    { code: 'IQD', name: $localize`:@@countrycurrencyservice.iqd:Iraq Dinars - IQD`},
    { code: 'IEP', name: $localize`:@@countrycurrencyservice.iep:Ireland Pounds - IEP`},
    { code: 'ILS', name: $localize`:@@countrycurrencyservice.ils:Israel New Shekels - ILS`},
    { code: 'JMD', name: $localize`:@@countrycurrencyservice.jmd:Jamaica Dollars - JMD`},
    { code: 'JPY', name: $localize`:@@countrycurrencyservice.jyp:Japan Yen - JPY`},
    { code: 'JOD', name: $localize`:@@countrycurrencyservice.jod:Jordan Dinars - JOD`},
    { code: 'KES', name: $localize`:@@countrycurrencyservice.kes:Kenya Shillings - KES`},
    { code: 'KWD', name: $localize`:@@countrycurrencyservice.kwd:Kuwait Dinars - KWD`},
    { code: 'LBP', name: $localize`:@@countrycurrencyservice.lbp:Lebanon Pounds - LBP`},
    { code: 'LUF', name: $localize`:@@countrycurrencyservice.luf:Luxembourg Francs - LUF`},
    { code: 'MYR', name: $localize`:@@countrycurrencyservice.myr:Malaysia Ringgits - MYR`},
    { code: 'MTL', name: $localize`:@@countrycurrencyservice.mtl:Malta Liri - MTL`},
    { code: 'MUR', name: $localize`:@@countrycurrencyservice.mur:Mauritius Rupees - MUR`},
    { code: 'MXN', name: $localize`:@@countrycurrencyservice.mxn:Mexico Pesos - MXN`},
    { code: 'MAD', name: $localize`:@@countrycurrencyservice.mad:Morocco Dirhams - MAD`},
    { code: 'NZD', name: $localize`:@@countrycurrencyservice.nzd:New Zealand Dollars - NZD`},
    { code: 'NOK', name: $localize`:@@countrycurrencyservice.nok:Norway Kroner - NOK`},
    { code: 'OMR', name: $localize`:@@countrycurrencyservice.omr:Oman Rials - OMR`},
    { code: 'PKR', name: $localize`:@@countrycurrencyservice.pkr:Pakistan Rupees - PKR`},
    { code: 'XPD', name: $localize`:@@countrycurrencyservice.xpd:Palladium Ounces - XPD`},
    { code: 'PEN', name: $localize`:@@countrycurrencyservice.pen:Peru Nuevos Soles - PEN`},
    { code: 'PHP', name: $localize`:@@countrycurrencyservice.php:Philippines Pesos - PHP`},
    { code: 'XPT', name: $localize`:@@countrycurrencyservice.xpt:Platinum Ounces - XPT`},
    { code: 'PLN', name: $localize`:@@countrycurrencyservice.pln:Poland Zlotych - PLN`},
    { code: 'QAR', name: $localize`:@@countrycurrencyservice.qar:Qatar Riyals - QAR`},
    { code: 'RON', name: $localize`:@@countrycurrencyservice.ron:Romania New Lei - RON`},
    { code: 'ROL', name: $localize`:@@countrycurrencyservice.rol:Romania Lei - ROL`},
    { code: 'RUB', name: $localize`:@@countrycurrencyservice.rub:Russia Rubles - RUB`},
    { code: 'SAR', name: $localize`:@@countrycurrencyservice.sar:Saudi Arabia Riyals - SAR`},
    { code: 'XAG', name: $localize`:@@countrycurrencyservice.xag:Silver Ounces - XAG`},
    { code: 'SGD', name: $localize`:@@countrycurrencyservice.sgd:Singapore Dollars - SGD`},
    { code: 'SKK', name: $localize`:@@countrycurrencyservice.skk:Slovakia Koruny - SKK`},
    { code: 'SIT', name: $localize`:@@countrycurrencyservice.sit:Slovenia Tolars - SIT`},
    { code: 'ZAR', name: $localize`:@@countrycurrencyservice.zar:South Africa Rand - ZAR`},
    { code: 'KRW', name: $localize`:@@countrycurrencyservice.krw:South Korea Won - KRW`},
    { code: 'LKR', name: $localize`:@@countrycurrencyservice.lkr:Sri Lanka Rupees - LKR`},
    { code: 'SDD', name: $localize`:@@countrycurrencyservice.sdd:Sudan Dinars - SDD`},
    { code: 'SEK', name: $localize`:@@countrycurrencyservice.sek:Sweden Kronor - SEK`},
    { code: 'CHF', name: $localize`:@@countrycurrencyservice.chf:Switzerland Francs - CHF`},
    { code: 'TWD', name: $localize`:@@countrycurrencyservice.twd:Taiwan New Dollars - TWD`},
    { code: 'THB', name: $localize`:@@countrycurrencyservice.thb:Thailand Baht - THB`},
    { code: 'TTD', name: $localize`:@@countrycurrencyservice.ttd:Trinidad and Tobago Dollars - TTD`},
    { code: 'TND', name: $localize`:@@countrycurrencyservice.tnd:Tunisia Dinars - TND`},
    { code: 'TRY', name: $localize`:@@countrycurrencyservice.try:Turkey New Lira - TRY`},
    { code: 'AED', name: $localize`:@@countrycurrencyservice.aed:United Arab Emirates Dirhams - AED`},
    { code: 'GBP', name: $localize`:@@countrycurrencyservice.gbp:United Kingdom Pounds - GBP`},
    { code: 'USD', name: $localize`:@@countryCurrencyService.usd:United States Dollars - USD`},
    { code: 'VEB', name: $localize`:@@countrycurrencyservice.veb:Venezuela Bolivares - VEB`},
    { code: 'VND', name: $localize`:@@countrycurrencyservice.vnd:Vietnam Dong - VND`},
    { code: 'ZMK', name: $localize`:@@countrycurrencyservice.zmk:Zambia Kwacha - ZMK`}
  ]

  countries = [
    { name: $localize`:@@countrycurrencyservice.AF:Afghanistan`, dial_code: "+93", code: "AF" },
    { name: $localize`:@@countrycurrencyservice.AX:Aland Islands`, dial_code: "+358", code: "AX" },
    { name: $localize`:@@countrycurrencyservice.al:Albania`, dial_code: "+355", code: "AL" },
    { name: $localize`:@@countrycurrencyservice.dz:Algeria`, dial_code: "+213", code: "DZ" },
    { name: $localize`:@@countrycurrencyservice.as:American Samoa`, dial_code: "+1684", code: "AS" },
    { name: $localize`:@@countrycurrencyservice.ad:Andorra`, dial_code: "+376", code: "AD" },
    { name: $localize`:@@countrycurrencyservice.ao:Angola`, dial_code: "+244", code: "AO" },
    { name: $localize`:@@countrycurrencyservice.ai:Anguilla`, dial_code: "+1264", code: "AI" },
    { name: $localize`:@@countrycurrencyservice.aq:Antarctica`, dial_code: "+672", code: "AQ" },
    { name: $localize`:@@countrycurrencyservice.ag:Antigua and Barbuda`, dial_code: "+1268", code: "AG" },
    { name: $localize`:@@countrycurrencyservice.ar:Argentina`, dial_code: "+54", code: "AR" },
    { name: $localize`:@@countrycurrencyservice.am:Armenia`, dial_code: "+374", code: "AM" },
    { name: $localize`:@@countrycurrencyservice.aw:Aruba`, dial_code: "+297", code: "AW" },
    { name: $localize`:@@countrycurrencyservice.au:Australia`, dial_code: "+61", code: "AU" },
    { name: $localize`:@@countrycurrencyservice.at:Austria`, dial_code: "+43", code: "AT" },
    { name: $localize`:@@countrycurrencyservice.az:Azerbaijan`, dial_code: "+994", code: "AZ" },
    { name: $localize`:@@countrycurrencyservice.bs:Bahamas`, dial_code: "+1242", code: "BS" },
    { name: $localize`:@@countrycurrencyservice.bh:Bahrain`, dial_code: "+973", code: "BH" },
    { name: $localize`:@@countrycurrencyservice.bd:Bangladesh`, dial_code: "+880", code: "BD" },
    { name: $localize`:@@countrycurrencyservice.bb:Barbados`, dial_code: "+1246", code: "BB" },
    { name: $localize`:@@countrycurrencyservice.by:Belarus`, dial_code: "+375", code: "BY" },
    { name: $localize`:@@countrycurrencyservice.be:Belgium`, dial_code: "+32", code: "BE" },
    { name: $localize`:@@countrycurrencyservice.bz:Belize`, dial_code: "+501", code: "BZ" },
    { name: $localize`:@@countrycurrencyservice.bj:Benin`, dial_code: "+229", code: "BJ" },
    { name: $localize`:@@countrycurrencyservice.bm:Bermuda`, dial_code: "+1441", code: "BM" },
    { name: $localize`:@@countrycurrencyservice.bt:Bhutan`, dial_code: "+975", code: "BT" },
    { name: $localize`:@@countrycurrencyservice.bo:Bolivia, Plurinational State of`, dial_code: "+591", code: "BO" },
    { name: $localize`:@@countrycurrencyservice.ba:Bosnia and Herzegovina`, dial_code: "+387", code: "BA" },
    { name: $localize`:@@countrycurrencyservice.bw:Botswana`, dial_code: "+267", code: "BW" },
    { name: $localize`:@@countrycurrencyservice.br:Brazil`, dial_code: "+55", code: "BR" },
    { name: $localize`:@@countrycurrencyservice.io:British Indian Ocean Territory`, dial_code: "+246", code: "IO" },
    { name: $localize`:@@countrycurrencyservice.bn:Brunei Darussalam`, dial_code: "+673", code: "BN" },
    { name: $localize`:@@countrycurrencyservice.bg:Bulgaria`, dial_code: "+359", code: "BG" },
    { name: $localize`:@@countrycurrencyservice.bf:Burkina Faso`, dial_code: "+226", code: "BF" },
    { name: $localize`:@@countrycurrencyservice.bi:Burundi`, dial_code: "+257", code: "BI" },
    { name: $localize`:@@countrycurrencyservice.kh:Cambodia`, dial_code: "+855", code: "KH" },
    { name: $localize`:@@countrycurrencyservice.cm:Cameroon`, dial_code: "+237", code: "CM" },
    { name: $localize`:@@countrycurrencyservice.ca:Canada`, dial_code: "+1", code: "CA" },
    { name: $localize`:@@countrycurrencyservice.cv:Cape Verde`, dial_code: "+238", code: "CV" },
    { name: $localize`:@@countrycurrencyservice.ky:Cayman Islands`, dial_code: "+ 345", code: "KY" },
    { name: $localize`:@@countrycurrencyservice.cf:Central African Republic`, dial_code: "+236", code: "CF" },
    { name: $localize`:@@countrycurrencyservice.td:Chad`, dial_code: "+235", code: "TD" },
    { name: $localize`:@@countrycurrencyservice.cl:Chile`, dial_code: "+56", code: "CL" },
    { name: $localize`:@@countrycurrencyservice.cn:China`, dial_code: "+86", code: "CN" },
    { name: $localize`:@@countrycurrencyservice.cx:Christmas Island`, dial_code: "+61", code: "CX" },
    { name: $localize`:@@countrycurrencyservice.cc:Cocos (Keeling) Islands`, dial_code: "+61", code: "CC" },
    { name: $localize`:@@countrycurrencyservice.co:Colombia`, dial_code: "+57", code: "CO" },
    { name: $localize`:@@countrycurrencyservice.km:Comoros`, dial_code: "+269", code: "KM" },
    { name: $localize`:@@countrycurrencyservice.cg:Congo`, dial_code: "+242", code: "CG" },
    { name: $localize`:@@countrycurrencyservice.cd:Congo, The Democratic Republic of the Congo`, dial_code: "+243", code: "CD" },
    { name: $localize`:@@countrycurrencyservice.ck:Cook Islands`, dial_code: "+682", code: "CK" },
    { name: $localize`:@@countrycurrencyservice.cr:Costa Rica`, dial_code: "+506", code: "CR" },
    { name: $localize`:@@countrycurrencyservice.ci:Cote d'Ivoire`, dial_code: "+225", code: "CI" },
    { name: $localize`:@@countrycurrencyservice.hr:Croatia`, dial_code: "+385", code: "HR" },
    { name: $localize`:@@countrycurrencyservice.cu:Cuba`, dial_code: "+53", code: "CU" },
    { name: $localize`:@@countrycurrencyservice.cy:Cyprus`, dial_code: "+357", code: "CY" },
    { name: $localize`:@@countrycurrencyservice.cz:Czech Republic`, dial_code: "+420", code: "CZ" },
    { name: $localize`:@@countrycurrencyservice.dk:Denmark`, dial_code: "+45", code: "DK" },
    { name: $localize`:@@countrycurrencyservice.dj:Djibouti`, dial_code: "+253", code: "DJ" },
    { name: $localize`:@@countrycurrencyservice.dm:Dominica`, dial_code: "+1767", code: "DM" },
    { name: $localize`:@@countrycurrencyservice.do:Dominican Republic`, dial_code: "+1849", code: "DO" },
    { name: $localize`:@@countrycurrencyservice.ec:Ecuador`, dial_code: "+593", code: "EC" },
    { name: $localize`:@@countrycurrencyservice.eg:Egypt`, dial_code: "+20", code: "EG" },
    { name: $localize`:@@countrycurrencyservice.sv:El Salvador`, dial_code: "+503", code: "SV" },
    { name: $localize`:@@countrycurrencyservice.gq:Equatorial Guinea`, dial_code: "+240", code: "GQ" },
    { name: $localize`:@@countrycurrencyservice.er:Eritrea`, dial_code: "+291", code: "ER" },
    { name: $localize`:@@countrycurrencyservice.ee:Estonia`, dial_code: "+372", code: "EE" },
    { name: $localize`:@@countrycurrencyservice.et:Ethiopia`, dial_code: "+251", code: "ET" },
    { name: $localize`:@@countrycurrencyservice.fk:Falkland Islands (Malvinas)`, dial_code: "+500", code: "FK" },
    { name: $localize`:@@countrycurrencyservice.fo:Faroe Islands`, dial_code: "+298", code: "FO" },
    { name: $localize`:@@countrycurrencyservice.fj:Fiji`, dial_code: "+679", code: "FJ" },
    { name: $localize`:@@countrycurrencyservice.fi:Finland`, dial_code: "+358", code: "FI" },
    { name: $localize`:@@countrycurrencyservice.fr:France`, dial_code: "+33", code: "FR" },
    { name: $localize`:@@countrycurrencyservice.gf:French Guiana`, dial_code: "+594", code: "GF" },
    { name: $localize`:@@countrycurrencyservice.pf:French Polynesia`, dial_code: "+689", code: "PF" },
    { name: $localize`:@@countrycurrencyservice.ga:Gabon`, dial_code: "+241", code: "GA" },
    { name: $localize`:@@countrycurrencyservice.gm:Gambia`, dial_code: "+220", code: "GM" },
    { name: $localize`:@@countrycurrencyservice.ge:Georgia`, dial_code: "+995", code: "GE" },
    { name: $localize`:@@countrycurrencyservice.de:Germany`, dial_code: "+49", code: "DE" },
    { name: $localize`:@@countrycurrencyservice.gh:Ghana`, dial_code: "+233", code: "GH" },
    { name: $localize`:@@countrycurrencyservice.gi:Gibraltar`, dial_code: "+350", code: "GI" },
    { name: $localize`:@@countrycurrencyservice.gr:Greece`, dial_code: "+30", code: "GR" },
    { name: $localize`:@@countrycurrencyservice.gl:Greenland`, dial_code: "+299", code: "GL" },
    { name: $localize`:@@countrycurrencyservice.gd:Grenada`, dial_code: "+1473", code: "GD" },
    { name: $localize`:@@countrycurrencyservice.gp:Guadeloupe`, dial_code: "+590", code: "GP" },
    { name: $localize`:@@countrycurrencyservice.gu:Guam`, dial_code: "+1671", code: "GU" },
    { name: $localize`:@@countrycurrencyservice.gt:Guatemala`, dial_code: "+502", code: "GT" },
    { name: $localize`:@@countrycurrencyservice.gg:Guernsey`, dial_code: "+44", code: "GG" },
    { name: $localize`:@@countrycurrencyservice.gn:Guinea`, dial_code: "+224", code: "GN" },
    { name: $localize`:@@countrycurrencyservice.gw:Guinea-Bissau`, dial_code: "+245", code: "GW" },
    { name: $localize`:@@countrycurrencyservice.gy:Guyana`, dial_code: "+595", code: "GY" },
    { name: $localize`:@@countrycurrencyservice.ht:Haiti`, dial_code: "+509", code: "HT" },
    { name: $localize`:@@countrycurrencyservice.va:Holy See (Vatican City State)`, dial_code: "+379", code: "VA" },
    { name: $localize`:@@countrycurrencyservice.hn:Honduras`, dial_code: "+504", code: "HN" },
    { name: $localize`:@@countrycurrencyservice.hk:Hong Kong`, dial_code: "+852", code: "HK" },
    { name: $localize`:@@countrycurrencyservice.hu:Hungary`, dial_code: "+36", code: "HU" },
    { name: $localize`:@@countrycurrencyservice.is:Iceland`, dial_code: "+354", code: "IS" },
    { name: $localize`:@@countrycurrencyservice.in:India`, dial_code: "+91", code: "IN" },
    { name: $localize`:@@countrycurrencyservice.id:Indonesia`, dial_code: "+62", code: "ID" },
    { name: $localize`:@@countrycurrencyservice.ir:Iran, Islamic Republic of Persian Gulf`, dial_code: "+98", code: "IR" },
    { name: $localize`:@@countrycurrencyservice.iq:Iraq`, dial_code: "+964", code: "IQ" },
    { name: $localize`:@@countrycurrencyservice.ie:Ireland`, dial_code: "+353", code: "IE" },
    { name: $localize`:@@countrycurrencyservice.im:Isle of Man`, dial_code: "+44", code: "IM" },
    { name: $localize`:@@countrycurrencyservice.il:Israel`, dial_code: "+972", code: "IL" },
    { name: $localize`:@@countrycurrencyservice.it:Italy`, dial_code: "+39", code: "IT" },
    { name: $localize`:@@countrycurrencyservice.jm:Jamaica`, dial_code: "+1876", code: "JM" },
    { name: $localize`:@@countrycurrencyservice.jp:Japan`, dial_code: "+81", code: "JP" },
    { name: $localize`:@@countrycurrencyservice.je:Jersey`, dial_code: "+44", code: "JE" },
    { name: $localize`:@@countrycurrencyservice.jo:Jordan`, dial_code: "+962", code: "JO" },
    { name: $localize`:@@countrycurrencyservice.kz:Kazakhstan`, dial_code: "+77", code: "KZ" },
    { name: $localize`:@@countrycurrencyservice.ke:Kenya`, dial_code: "+254", code: "KE" },
    { name: $localize`:@@countrycurrencyservice.ki:Kiribati`, dial_code: "+686", code: "KI" },
    { name: $localize`:@@countrycurrencyservice.kp:Korea, Democratic People's Republic of Korea`, dial_code: "+850", code: "KP" },
    { name: $localize`:@@countrycurrencyservice.kr:Korea, Republic of South Korea`, dial_code: "+82", code: "KR" },
    { name: $localize`:@@countrycurrencyservice.kw:Kuwait`, dial_code: "+965", code: "KW" },
    { name: $localize`:@@countrycurrencyservice.kg:Kyrgyzstan`, dial_code: "+996", code: "KG" },
    { name: $localize`:@@countrycurrencyservice.la:Laos`, dial_code: "+856", code: "LA" },
    { name: $localize`:@@countrycurrencyservice.lv:Latvia`, dial_code: "+371", code: "LV" },
    { name: $localize`:@@countrycurrencyservice.lb:Lebanon`, dial_code: "+961", code: "LB" },
    { name: $localize`:@@countrycurrencyservice.ls:Lesotho`, dial_code: "+266", code: "LS" },
    { name: $localize`:@@countrycurrencyservice.lr:Liberia`, dial_code: "+231", code: "LR" },
    { name: $localize`:@@countrycurrencyservice.ly:Libyan Arab Jamahiriya`, dial_code: "+218", code: "LY" },
    { name: $localize`:@@countrycurrencyservice.li:Liechtenstein`, dial_code: "+423", code: "LI" },
    { name: $localize`:@@countrycurrencyservice.lt:Lithuania`, dial_code: "+370", code: "LT" },
    { name: $localize`:@@countrycurrencyservice.lu:Luxembourg`, dial_code: "+352", code: "LU" },
    { name: $localize`:@@countrycurrencyservice.mo:Macao`, dial_code: "+853", code: "MO" },
    { name: $localize`:@@countrycurrencyservice.mk:Macedonia`, dial_code: "+389", code: "MK" },
    { name: $localize`:@@countrycurrencyservice.mg:Madagascar`, dial_code: "+261", code: "MG" },
    { name: $localize`:@@countrycurrencyservice.mw:Malawi`, dial_code: "+265", code: "MW" },
    { name: $localize`:@@countrycurrencyservice.my:Malaysia`, dial_code: "+60", code: "MY" },
    { name: $localize`:@@countrycurrencyservice.mv:Maldives`, dial_code: "+960", code: "MV" },
    { name: $localize`:@@countrycurrencyservice.ml:Mali`, dial_code: "+223", code: "ML" },
    { name: $localize`:@@countrycurrencyservice.mt:Malta`, dial_code: "+356", code: "MT" },
    { name: $localize`:@@countrycurrencyservice.mh:Marshall Islands`, dial_code: "+692", code: "MH" },
    { name: $localize`:@@countrycurrencyservice.mq:Martinique`, dial_code: "+596", code: "MQ" },
    { name: $localize`:@@countrycurrencyservice.mr:Mauritania`, dial_code: "+222", code: "MR" },
    { name: $localize`:@@countrycurrencyservice.mu:Mauritius`, dial_code: "+230", code: "MU" },
    { name: $localize`:@@countrycurrencyservice.yt:Mayotte`, dial_code: "+262", code: "YT" },
    { name: $localize`:@@countrycurrencyservice.mx:Mexico`, dial_code: "+52", code: "MX" },
    { name: $localize`:@@countrycurrencyservice.fm:Micronesia, Federated States of Micronesia`, dial_code: "+691", code: "FM" },
    { name: $localize`:@@countrycurrencyservice.md:Moldova`, dial_code: "+373", code: "MD" },
    { name: $localize`:@@countrycurrencyservice.mc:Monaco`, dial_code: "+377", code: "MC" },
    { name: $localize`:@@countrycurrencyservice.mn:Mongolia`, dial_code: "+976", code: "MN" },
    { name: $localize`:@@countrycurrencyservice.me:Montenegro`, dial_code: "+382", code: "ME" },
    { name: $localize`:@@countrycurrencyservice.ms:Montserrat`, dial_code: "+1664", code: "MS" },
    { name: $localize`:@@countrycurrencyservice.ma:Morocco`, dial_code: "+212", code: "MA" },
    { name: $localize`:@@countrycurrencyservice.mz:Mozambique`, dial_code: "+258", code: "MZ" },
    { name: $localize`:@@countrycurrencyservice.mm:Myanmar`, dial_code: "+95", code: "MM" },
    { name: $localize`:@@countrycurrencyservice.na:Namibia`, dial_code: "+264", code: "NA" },
    { name: $localize`:@@countrycurrencyservice.nr:Nauru`, dial_code: "+674", code: "NR" },
    { name: $localize`:@@countrycurrencyservice.np:Nepal`, dial_code: "+977", code: "NP" },
    { name: $localize`:@@countrycurrencyservice.nl:Netherlands`, dial_code: "+31", code: "NL" },
    { name: $localize`:@@countrycurrencyservice.an:Netherlands Antilles`, dial_code: "+599", code: "AN" },
    { name: $localize`:@@countrycurrencyservice.nc:New Caledonia`, dial_code: "+687", code: "NC" },
    { name: $localize`:@@countrycurrencyservice.nz:New Zealand`, dial_code: "+64", code: "NZ" },
    { name: $localize`:@@countrycurrencyservice.ni:Nicaragua`, dial_code: "+505", code: "NI" },
    { name: $localize`:@@countrycurrencyservice.ne:Niger`, dial_code: "+227", code: "NE" },
    { name: $localize`:@@countrycurrencyservice.ng:Nigeria`, dial_code: "+234", code: "NG" },
    { name: $localize`:@@countrycurrencyservice.nu:Niue`, dial_code: "+683", code: "NU" },
    { name: $localize`:@@countrycurrencyservice.nf:Norfolk Island`, dial_code: "+672", code: "NF" },
    { name: $localize`:@@countrycurrencyservice.mp:Northern Mariana Islands`, dial_code: "+1670", code: "MP" },
    { name: $localize`:@@countrycurrencyservice.no:Norway`, dial_code: "+47", code: "NO" },
    { name: $localize`:@@countrycurrencyservice.om:Oman`, dial_code: "+968", code: "OM" },
    { name: $localize`:@@countrycurrencyservice.pk:Pakistan`, dial_code: "+92", code: "PK" },
    { name: $localize`:@@countrycurrencyservice.pw:Palau`, dial_code: "+680", code: "PW" },
    { name: $localize`:@@countrycurrencyservice.ps:Palestinian Territory, Occupied`, dial_code: "+970", code: "PS" },
    { name: $localize`:@@countrycurrencyservice.pa:Panama`, dial_code: "+507", code: "PA" },
    { name: $localize`:@@countrycurrencyservice.pg:Papua New Guinea`, dial_code: "+675", code: "PG" },
    { name: $localize`:@@countrycurrencyservice.py:Paraguay`, dial_code: "+595", code: "PY" },
    { name: $localize`:@@countrycurrencyservice.pe:Peru`, dial_code: "+51", code: "PE" },
    { name: $localize`:@@countrycurrencyservice.ph:Philippines`, dial_code: "+63", code: "PH" },
    { name: $localize`:@@countrycurrencyservice.pn:Pitcairn`, dial_code: "+872", code: "PN" },
    { name: $localize`:@@countrycurrencyservice.pl:Poland`, dial_code: "+48", code: "PL" },
    { name: $localize`:@@countrycurrencyservice.pt:Portugal`, dial_code: "+351", code: "PT" },
    { name: $localize`:@@countrycurrencyservice.pr:Puerto Rico`, dial_code: "+1939", code: "PR" },
    { name: $localize`:@@countrycurrencyservice.qa:Qatar`, dial_code: "+974", code: "QA" },
    { name: $localize`:@@countrycurrencyservice.ro:Romania`, dial_code: "+40", code: "RO" },
    { name: $localize`:@@countrycurrencyservice.ru:Russia`, dial_code: "+7", code: "RU" },
    { name: $localize`:@@countrycurrencyservice.rw:Rwanda`, dial_code: "+250", code: "RW" },
    { name: $localize`:@@countrycurrencyservice.re:Reunion`, dial_code: "+262", code: "RE" },
    { name: $localize`:@@countrycurrencyservice.bl:Saint Barthelemy`, dial_code: "+590", code: "BL" },
    { name: $localize`:@@countrycurrencyservice.sh:Saint Helena, Ascension and Tristan Da Cunha`, dial_code: "+290", code: "SH" },
    { name: $localize`:@@countrycurrencyservice.kn:Saint Kitts and Nevis`, dial_code: "+1869", code: "KN" },
    { name: $localize`:@@countrycurrencyservice.lc:Saint Lucia`, dial_code: "+1758", code: "LC" },
    { name: $localize`:@@countrycurrencyservice.mf:Saint Martin`, dial_code: "+590", code: "MF" },
    { name: $localize`:@@countrycurrencyservice.pm:Saint Pierre and Miquelon`, dial_code: "+508", code: "PM" },
    { name: $localize`:@@countrycurrencyservice.vc:Saint Vincent and the Grenadines`, dial_code: "+1784", code: "VC" },
    { name: $localize`:@@countrycurrencyservice.ws:Samoa`, dial_code: "+685", code: "WS" },
    { name: $localize`:@@countrycurrencyservice.sm:San Marino`, dial_code: "+378", code: "SM" },
    { name: $localize`:@@countrycurrencyservice.st:Sao Tome and Principe`, dial_code: "+239", code: "ST" },
    { name: $localize`:@@countrycurrencyservice.sa:Saudi Arabia`, dial_code: "+966", code: "SA" },
    { name: $localize`:@@countrycurrencyservice.sn:Senegal`, dial_code: "+221", code: "SN" },
    { name: $localize`:@@countrycurrencyservice.rs:Serbia`, dial_code: "+381", code: "RS" },
    { name: $localize`:@@countrycurrencyservice.sc:Seychelles`, dial_code: "+248", code: "SC" },
    { name: $localize`:@@countrycurrencyservice.sl:Sierra Leone`, dial_code: "+232", code: "SL" },
    { name: $localize`:@@countrycurrencyservice.sg:Singapore`, dial_code: "+65", code: "SG" },
    { name: $localize`:@@countrycurrencyservice.sk:Slovakia`, dial_code: "+421", code: "SK" },
    { name: $localize`:@@countrycurrencyservice.si:Slovenia`, dial_code: "+386", code: "SI" },
    { name: $localize`:@@countrycurrencyservice.sb:Solomon Islands`, dial_code: "+677", code: "SB" },
    { name: $localize`:@@countrycurrencyservice.so:Somalia`, dial_code: "+252", code: "SO" },
    { name: $localize`:@@countrycurrencyservice.za:South Africa`, dial_code: "+27", code: "ZA" },
    { name: $localize`:@@countrycurrencyservice.ss:South Sudan`, dial_code: "+211", code: "SS" },
    { name: $localize`:@@countrycurrencyservice.gs:South Georgia and the South Sandwich Islands`, dial_code: "+500", code: "GS" },
    { name: $localize`:@@countrycurrencyservice.es:Spain`, dial_code: "+34", code: "ES" },
    { name: $localize`:@@countrycurrencyservice.lk:Sri Lanka`, dial_code: "+94", code: "LK" },
    { name: $localize`:@@countrycurrencyservice.sd:Sudan`, dial_code: "+249", code: "SD" },
    { name: $localize`:@@countrycurrencyservice.sr:Suriname`, dial_code: "+597", code: "SR" },
    { name: $localize`:@@countrycurrencyservice.sj:Svalbard and Jan Mayen`, dial_code: "+47", code: "SJ" },
    { name: $localize`:@@countrycurrencyservice.sz:Swaziland`, dial_code: "+268", code: "SZ" },
    { name: $localize`:@@countrycurrencyservice.se:Sweden`, dial_code: "+46", code: "SE" },
    { name: $localize`:@@countrycurrencyservice.ch:Switzerland`, dial_code: "+41", code: "CH" },
    { name: $localize`:@@countrycurrencyservice.sy:Syrian Arab Republic`, dial_code: "+963", code: "SY" },
    { name: $localize`:@@countrycurrencyservice.ty:Taiwan`, dial_code: "+886", code: "TW" },
    { name: $localize`:@@countrycurrencyservice.tj:Tajikistan`, dial_code: "+992", code: "TJ" },
    { name: $localize`:@@countrycurrencyservice.tz:Tanzania, United Republic of Tanzania`, dial_code: "+255", code: "TZ" },
    { name: $localize`:@@countrycurrencyservice.th:Thailand`, dial_code: "+66", code: "TH" },
    { name: $localize`:@@countrycurrencyservice.tl:Timor-Leste`, dial_code: "+670", code: "TL" },
    { name: $localize`:@@countrycurrencyservice.tg:Togo`, dial_code: "+228", code: "TG" },
    { name: $localize`:@@countrycurrencyservice.tk:Tokelau`, dial_code: "+690", code: "TK" },
    { name: $localize`:@@countrycurrencyservice.to:Tonga`, dial_code: "+676", code: "TO" },
    { name: $localize`:@@countrycurrencyservice.tt:Trinidad and Tobago`, dial_code: "+1868", code: "TT" },
    { name: $localize`:@@countrycurrencyservice.tn:Tunisia`, dial_code: "+216", code: "TN" },
    { name: $localize`:@@countrycurrencyservice.tr:Turkey`, dial_code: "+90", code: "TR" },
    { name: $localize`:@@countrycurrencyservice.tm:Turkmenistan`, dial_code: "+993", code: "TM" },
    { name: $localize`:@@countrycurrencyservice.tc:Turks and Caicos Islands`, dial_code: "+1649", code: "TC" },
    { name: $localize`:@@countrycurrencyservice.tv:Tuvalu`, dial_code: "+688", code: "TV" },
    { name: $localize`:@@countrycurrencyservice.ug:Uganda`, dial_code: "+256", code: "UG" },
    { name: $localize`:@@countrycurrencyservice.ua:Ukraine`, dial_code: "+380", code: "UA" },
    { name: $localize`:@@countrycurrencyservice.ae:United Arab Emirates`, dial_code: "+971", code: "AE" },
    { name: $localize`:@@countrycurrencyservice.gb:United Kingdom`, dial_code: "+44", code: "GB" },
    { name: $localize`:@@countrycurrencyservice.us:United States of America`, dial_code: "+1", code: "USA" },
    { name: $localize`:@@countrycurrencyservice.uy:Uruguay`, dial_code: "+598", code: "UY" },
    { name: $localize`:@@countrycurrencyservice.uz:Uzbekistan`, dial_code: "+998", code: "UZ" },
    { name: $localize`:@@countrycurrencyservice.vu:Vanuatu`, dial_code: "+678", code: "VU" },
    { name: $localize`:@@countrycurrencyservice.ve:Venezuela, Bolivarian Republic of Venezuela`, dial_code: "+58", code: "VE" },
    { name: $localize`:@@countrycurrencyservice.vn:Vietnam`, dial_code: "+84", code: "VN" },
    { name: $localize`:@@countrycurrencyservice.vg:Virgin Islands, British`, dial_code: "+1284", code: "VG" },
    { name: $localize`:@@countrycurrencyservice.vi:Virgin Islands, U.S.`, dial_code: "+1340", code: "VI" },
    { name: $localize`:@@countrycurrencyservice.wf:Wallis and Futuna`, dial_code: "+681", code: "WF" },
    { name: $localize`:@@countrycurrencyservice.ye:Yemen`, dial_code: "+967", code: "YE" },
    { name: $localize`:@@countrycurrencyservice.zm:Zambia`, dial_code: "+260", code: "ZM" },
    { name: $localize`:@@countrycurrencyservice.zw:Zimbabwe`, dial_code: "+263", code: "ZW" }
  ]

  constructor(private _http: HttpClient) { }

  getCurrencies() {
    return this.currencies;
  }

  getCountries() {
    return this.countries
  }
}
