version: '3.7'
# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2022-12-12T19-27-27Z
  command: server --address 0.0.0.0:9000 --console-address ":9001" http://minio{1...3}/data1
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: ${MINIO_USER}
    MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

services:

  mongo-setup:
    image: ${DOCKER_USER}/${DOCKER_REPO}:mongodb
    restart: on-failure
    networks:
      - octonius_production
    volumes:
      - ./mongo_setup_scripts:/scripts
    entrypoint: [ "/scripts/setup.sh" ]
    depends_on:
      - mongo-0-mongo
      - mongo-1-mongo
      - mongo-2-mongo
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          memory: 128M
  
  mongo-2-mongo:
    hostname: mongo-2-mongo
    image: ${DOCKER_USER}/${DOCKER_REPO}:mongodb
    volumes:
      - octonius_production_db_data2:/data/db
    ports:
      - ${MONGO_PORT3}:${MONGO_MACHINE_PORT}
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "prod_octo_rs", "--journal", "--dbpath", "/data/db" ]
    networks:
      - octonius_production
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          memory: 128M
    networks:
      - octonius_production

  mongo-1-mongo:
    hostname: mongo-1-mongo
    image: ${DOCKER_USER}/${DOCKER_REPO}:mongodb
    volumes:
      - octonius_production_db_data1:/data/db
    ports:
      - ${MONGO_PORT2}:${MONGO_MACHINE_PORT}
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "prod_octo_rs", "--journal", "--dbpath", "/data/db" ]
    networks:
      - octonius_production
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          memory: 128M
    networks:
      - octonius_production

  mongo-0-mongo:
    hostname: mongo-0-mongo
    image: ${DOCKER_USER}/${DOCKER_REPO}:mongodb
    volumes:
      - octonius_production_db_data0:/data/db
    ports:
      - ${MONGO_PORT1}:${MONGO_MACHINE_PORT}
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "prod_octo_rs", "--journal", "--dbpath", "/data/db" ]
    networks:
      - octonius_production
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          memory: 128M
    networks:
      - octonius_production

  approval-server:
    image: ${DOCKER_USER}/${DOCKER_REPO}:approval-server
    ports:
      - ${APPROVAL_SERVER_PORT}:${MACHINE_PORT}
    volumes:
      - ${VOLUME_NODE_MODULES}
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${MACHINE_PORT}
      - HOST=${HOST}
      - JWT_KEY=${JWT_KEY}
      - DB_URL=${DB_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - HEADER_EXTERNAL_KEY=${HEADER_EXTERNAL_KEY}
      - PROTOCOL=${PROTOCOL}
      - DOMAIN=${DOMAIN}
      - MANAGEMENT_URL=${MANAGEMENT_URL}
      - PROXY_AVAILABLE=${PROXY_AVAILABLE}
      - PROXY_PROTOCOL=${PROXY_PROTOCOL}
      - PROXY_HOST=${PROXY_HOST}
      - PROXY_PORT=${PROXY_PORT}
    deploy:
      replicas: ${REPLICAS}
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - octonius_production

  auths-server:
    image: ${DOCKER_USER}/${DOCKER_REPO}:auths-server
    ports:
      - ${AUTHS_SERVER_PORT}:${MACHINE_PORT}
    volumes:
      - ${VOLUME_NODE_MODULES}
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${MACHINE_PORT}
      - HOST=${HOST}
      - JWT_KEY=${JWT_KEY}
      - DB_URL=${DB_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - HEADER_EXTERNAL_KEY=${HEADER_EXTERNAL_KEY}
      - PROTOCOL=${PROTOCOL}
      - DOMAIN=${DOMAIN}
      - MANAGEMENT_URL=${MANAGEMENT_URL}
      - PROXY_AVAILABLE=${PROXY_AVAILABLE}
      - PROXY_PROTOCOL=${PROXY_PROTOCOL}
      - PROXY_HOST=${PROXY_HOST}
      - PROXY_PORT=${PROXY_PORT}
    deploy:
      replicas: ${REPLICAS}
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - octonius_production
         
  groups-server:
    image: ${DOCKER_USER}/${DOCKER_REPO}:groups-server
    ports:
      - ${GROUPS_SERVER_PORT}:${MACHINE_PORT}
    volumes:
      - ${VOLUME_NODE_MODULES}
      - octonius_production_groups_uploads_data:${VOLUME_UPLOADS}
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${MACHINE_PORT}
      - HOST=${HOST}
      - JWT_KEY=${JWT_KEY}
      - DB_URL=${DB_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - HEADER_EXTERNAL_KEY=${HEADER_EXTERNAL_KEY}
      - PROTOCOL=${PROTOCOL}
      - DOMAIN=${DOMAIN}
      - MANAGEMENT_URL=${MANAGEMENT_URL}
      - PROXY_AVAILABLE=${PROXY_AVAILABLE}
      - PROXY_PROTOCOL=${PROXY_PROTOCOL}
      - PROXY_HOST=${PROXY_HOST}
      - PROXY_PORT=${PROXY_PORT}
    deploy:
      replicas: ${REPLICAS}
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - octonius_production
      
  workspaces-server:
    image: ${DOCKER_USER}/${DOCKER_REPO}:workspaces-server
    ports:
      - ${WORKSPACES_SERVER_PORT}:${MACHINE_PORT}
    volumes:
      - ${VOLUME_NODE_MODULES}
      - octonius_production_workspaces_uploads_data:${VOLUME_UPLOADS}
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${MACHINE_PORT}
      - HOST=${HOST}
      - JWT_KEY=${JWT_KEY}
      - DB_URL=${DB_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - HEADER_EXTERNAL_KEY=${HEADER_EXTERNAL_KEY}
      - PROTOCOL=${PROTOCOL}
      - DOMAIN=${DOMAIN}
      - MANAGEMENT_URL=${MANAGEMENT_URL}
      - PROXY_AVAILABLE=${PROXY_AVAILABLE}
      - PROXY_PROTOCOL=${PROXY_PROTOCOL}
      - PROXY_HOST=${PROXY_HOST}
      - PROXY_PORT=${PROXY_PORT}
    deploy:
      replicas: ${REPLICAS}
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - octonius_production
      
  users-server:
    image: ${DOCKER_USER}/${DOCKER_REPO}:users-server
    ports:
      - ${USERS_SERVER_PORT}:${MACHINE_PORT}
    volumes:
      - ${VOLUME_NODE_MODULES}
      - octonius_production_users_uploads_data:${VOLUME_UPLOADS}
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${MACHINE_PORT}
      - HOST=${HOST}
      - JWT_KEY=${JWT_KEY}
      - DB_URL=${DB_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - HEADER_EXTERNAL_KEY=${HEADER_EXTERNAL_KEY}
      - PROTOCOL=${PROTOCOL}
      - DOMAIN=${DOMAIN}
      - MANAGEMENT_URL=${MANAGEMENT_URL}
      - PROXY_AVAILABLE=${PROXY_AVAILABLE}
      - PROXY_PROTOCOL=${PROXY_PROTOCOL}
      - PROXY_HOST=${PROXY_HOST}
      - PROXY_PORT=${PROXY_PORT}
    deploy:
      replicas: ${REPLICAS}
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - octonius_production
      
  posts-server:
    image: ${DOCKER_USER}/${DOCKER_REPO}:posts-server
    ports:
      - ${POSTS_SERVER_PORT}:${MACHINE_PORT}
    volumes:
      - ${VOLUME_NODE_MODULES}
      - octonius_production_posts_uploads_data:${VOLUME_UPLOADS}
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${MACHINE_PORT}
      - HOST=${HOST}
      - JWT_KEY=${JWT_KEY}
      - DB_URL=${DB_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - HEADER_EXTERNAL_KEY=${HEADER_EXTERNAL_KEY}
      - PROTOCOL=${PROTOCOL}
      - DOMAIN=${DOMAIN}
      - MANAGEMENT_URL=${MANAGEMENT_URL}
      - PROXY_AVAILABLE=${PROXY_AVAILABLE}
      - PROXY_PROTOCOL=${PROXY_PROTOCOL}
      - PROXY_HOST=${PROXY_HOST}
      - PROXY_PORT=${PROXY_PORT}
    deploy:
      replicas: ${REPLICAS}
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - octonius_production
      
  notifications-server:
    image: ${DOCKER_USER}/${DOCKER_REPO}:notifications-server
    ports:
      - ${NOTIFICATIONS_SERVER_PORT}:${MACHINE_PORT}
    volumes:
      - ${VOLUME_NODE_MODULES}
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${MACHINE_PORT}
      - HOST=${HOST}
      - JWT_KEY=${JWT_KEY}
      - DB_URL=${DB_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - HEADER_EXTERNAL_KEY=${HEADER_EXTERNAL_KEY}
      - PROTOCOL=${PROTOCOL}
      - DOMAIN=${DOMAIN}
      - MANAGEMENT_URL=${MANAGEMENT_URL}
      - PROXY_AVAILABLE=${PROXY_AVAILABLE}
      - PROXY_PROTOCOL=${PROXY_PROTOCOL}
      - PROXY_HOST=${PROXY_HOST}
      - PROXY_PORT=${PROXY_PORT}
    deploy:
      replicas: ${REPLICAS}
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - octonius_production
      
  utilities-server:
    image: ${DOCKER_USER}/${DOCKER_REPO}:utilities-server
    ports:
      - ${UTILITIES_SERVER_PORT}:${MACHINE_PORT}
    volumes:
      - ${VOLUME_NODE_MODULES}
      - octonius_production_utilities_uploads_data:${VOLUME_UPLOADS}
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${MACHINE_PORT}
      - HOST=${HOST}
      - JWT_KEY=${JWT_KEY}
      - DB_URL=${DB_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - HEADER_EXTERNAL_KEY=${HEADER_EXTERNAL_KEY}
      - PROTOCOL=${PROTOCOL}
      - DOMAIN=${DOMAIN}
      - MANAGEMENT_URL=${MANAGEMENT_URL}
      - PROXY_AVAILABLE=${PROXY_AVAILABLE}
      - PROXY_PROTOCOL=${PROXY_PROTOCOL}
      - PROXY_HOST=${PROXY_HOST}
      - PROXY_PORT=${PROXY_PORT}
    deploy:
      replicas: ${REPLICAS}
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - octonius_production

  folio-server:
    image: ${DOCKER_USER}/${DOCKER_REPO}:folio-server
    ports:
      - ${FOLIO_SERVER_PORT}:${MACHINE_PORT}
    volumes:
      - ${VOLUME_NODE_MODULES}
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${MACHINE_PORT}
      - HOST=${HOST}
      - JWT_KEY=${JWT_KEY}
      - DB_URL=${DB_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - HEADER_EXTERNAL_KEY=${HEADER_EXTERNAL_KEY}
      - PROTOCOL=${PROTOCOL}
      - DOMAIN=${DOMAIN}
      - MANAGEMENT_URL=${MANAGEMENT_URL}
      - PROXY_AVAILABLE=${PROXY_AVAILABLE}
      - PROXY_PROTOCOL=${PROXY_PROTOCOL}
      - PROXY_HOST=${PROXY_HOST}
      - PROXY_PORT=${PROXY_PORT}
    deploy:
      replicas: ${REPLICAS}
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - octonius_production

  search-server:
    image: ${DOCKER_USER}/${DOCKER_REPO}:search-server
    ports:
      - ${SEARCH_SERVER_PORT}:${MACHINE_PORT}
    volumes:
      - ${VOLUME_NODE_MODULES}
      - octonius_production_search_uploads_data:${VOLUME_UPLOADS}
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${MACHINE_PORT}
      - HOST=${HOST}
      - JWT_KEY=${JWT_KEY}
      - DB_URL=${DB_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - HEADER_EXTERNAL_KEY=${HEADER_EXTERNAL_KEY}
      - PROTOCOL=${PROTOCOL}
      - DOMAIN=${DOMAIN}
      - MANAGEMENT_URL=${MANAGEMENT_URL}
      - PROXY_AVAILABLE=${PROXY_AVAILABLE}
      - PROXY_PROTOCOL=${PROXY_PROTOCOL}
      - PROXY_HOST=${PROXY_HOST}
      - PROXY_PORT=${PROXY_PORT}
    deploy:
      replicas: ${REPLICAS}
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - octonius_production
      
  integrations-server:
    image: ${DOCKER_USER}/${DOCKER_REPO}:integrations-server
    ports:
      - ${INTEGRATIONS_SERVER_PORT}:${MACHINE_PORT}
    volumes:
      - ${VOLUME_NODE_MODULES}
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${MACHINE_PORT}
      - HOST=${HOST}
      - JWT_KEY=${JWT_KEY}
      - DB_URL=${DB_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - HEADER_EXTERNAL_KEY=${HEADER_EXTERNAL_KEY}
      - PROTOCOL=${PROTOCOL}
      - DOMAIN=${DOMAIN}
      - TEAMS_BOT_URL=${TEAMS_BOT_URL}
      - SLACK_BOT_ACCESS_TOKEN=${SLACK_BOT_ACCESS_TOKEN}
      - MANAGEMENT_URL=${MANAGEMENT_URL}
      - PROXY_AVAILABLE=${PROXY_AVAILABLE}
      - PROXY_PROTOCOL=${PROXY_PROTOCOL}
      - PROXY_HOST=${PROXY_HOST}
      - PROXY_PORT=${PROXY_PORT}
    deploy:
      replicas: ${REPLICAS}
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - octonius_production
  
  flamingo-server:
    image: ${DOCKER_USER}/${DOCKER_REPO}:flamingo-server
    ports:
      - ${FLAMINGO_SERVER_PORT}:${MACHINE_PORT}
    volumes:
      - ${VOLUME_NODE_MODULES}
      - octonius_production_flamingo_uploads_data:${VOLUME_UPLOADS}
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${MACHINE_PORT}
      - HOST=${HOST}
      - JWT_KEY=${JWT_KEY}
      - DB_URL=${DB_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - HEADER_EXTERNAL_KEY=${HEADER_EXTERNAL_KEY}
      - PROTOCOL=${PROTOCOL}
      - DOMAIN=${DOMAIN}
      - MANAGEMENT_URL=${MANAGEMENT_URL}
      - PROXY_AVAILABLE=${PROXY_AVAILABLE}
      - PROXY_PROTOCOL=${PROXY_PROTOCOL}
      - PROXY_HOST=${PROXY_HOST}
      - PROXY_PORT=${PROXY_PORT}
    deploy:
      replicas: ${REPLICAS}
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - octonius_production
      
  client:
    image: ${DOCKER_USER}/${DOCKER_REPO}:client
    volumes:
      - ${VOLUME_NODE_MODULES}
    environment: 
      - PROTOCOL=${PROTOCOL}
      - DOMAIN=${DOMAIN}
      - WEBSOCKET=${WEBSOCKET}
      - mgmt_portal_domain=${mgmt_portal_domain}
    deploy:
      replicas: ${REPLICAS}
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - octonius_production

  nginx:
    image: ${DOCKER_USER}/${DOCKER_REPO}:nginx
    ports:
      - ${APPLICATION_PORT}:${NGINX_PORT}
    deploy:
      replicas: ${REPLICAS}
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - octonius_production

  balancer:
    hostname: balancer
    image: minio/sidekick:v2.0.2
    command: --address :8000 --health-path=/minio/health/live --insecure --log http://minio{1...3}:9000
    ports:
      - "127.0.0.1:8181:9001"
    depends_on:
      - minio1
      - minio2
      - minio3 
    deploy:
      mode: global         
    networks:
      - octonius_production

  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - data1-1:/data1
    deploy:
      placement:
        constraints:
          - node.hostname==manager
    networks:
      - octonius_production

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - data2-1:/data1
    deploy:
      placement:
        constraints:
          - node.hostname==manager
    networks:
      - octonius_production

  minio3:
    <<: *minio-common
    hostname: minio3
    volumes:
      - data3-1:/data1
    deploy:
      placement:
        constraints:
          - node.hostname==manager
    networks:
      - octonius_production



volumes:
  octonius_production_db_data2:
    driver: local
    driver_opts:
      type: none
      device: /mnt/volume_fra1_01/data/mongo/db2
      o: bind

  octonius_production_db_data1:
    driver: local
    driver_opts:
      type: none
      device: /mnt/volume_fra1_01/data/mongo/db1
      o: bind

  octonius_production_db_data0:
    driver: local
    driver_opts:
      type: none
      device: /mnt/volume_fra1_01/data/mongo/db0
      o: bind

  octonius_production_groups_uploads_data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/volume_fra1_01/data/uploads/groups
      o: bind
  
  octonius_production_posts_uploads_data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/volume_fra1_01/data/uploads/posts
      o: bind

  octonius_production_users_uploads_data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/volume_fra1_01/data/uploads/users
      o: bind

  octonius_production_workspaces_uploads_data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/volume_fra1_01/data/uploads/workspaces
      o: bind

  octonius_production_utilities_uploads_data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/volume_fra1_01/data/uploads/utilities
      o: bind

  octonius_production_flamingo_uploads_data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/volume_fra1_01/data/uploads/flamingo
      o: bind
  
  octonius_production_search_uploads_data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/volume_fra1_01/data/uploads/search
      o: bind 

  data1-1:
    driver: local
    driver_opts:
      type: none
      device: /mnt/volume_fra1_01/data/minio/data1
      o: bind

  data2-1:
    driver: local
    driver_opts:
      type: none
      device: /mnt/volume_fra1_01/data/minio/data2
      o: bind

  data3-1:
    driver: local
    driver_opts:
      type: none
      device: /mnt/volume_fra1_01/data/minio/data3
      o: bind  



networks:
  octonius_production:
    driver: overlay
    internal: true
