version: '3.7'

services:
  mongo-setup:
    container_name: mongo-setup
    image: ${DOCKER_USER}/${DOCKER_REPO}:mongodb
    restart: on-failure
    networks:
       - acc
    volumes:
      - ./mongo_setup_scripts:/scripts
    entrypoint: [ "/scripts/setup.sh" ]
    depends_on:
      - mongo-0.mongo
      - mongo-1.mongo
      - mongo-2.mongo
  mongo-2.mongo:
    hostname: mongo-2.mongo
    container_name: mongo-2.mongo
    image: ${DOCKER_USER}/${DOCKER_REPO}:mongodb
    restart: always
    expose: 
    - 27017
    volumes:
      - ./acc_db_data/mongodb/data2/db:/data/db
    ports:
      - ${MONGO_PORT3}:${MONGO_MACHINE_PORT}
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "octo_rs", "--journal", "--dbpath", "/data/db" ]
    networks:
      - acc

  mongo-1.mongo:
    hostname: mongo-1.mongo
    container_name: mongo-1.mongo
    image: ${DOCKER_USER}/${DOCKER_REPO}:mongodb
    restart: always
    expose:
    - 27017
    volumes:
      - ./acc_db_data/mongodb/data1/db:/data/db
    ports:
      - ${MONGO_PORT2}:${MONGO_MACHINE_PORT}
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "octo_rs", "--journal", "--dbpath", "/data/db" ]
    networks:
      - acc
  
  mongo-0.mongo:
    hostname: mongo-0.mongo
    container_name: mongo-0.mongo
    image: ${DOCKER_USER}/${DOCKER_REPO}:mongodb
    restart: always
    expose:
    - 27017
    volumes:
      - "./acc_db_data/mongodb/data0/db:/data/db"
    ports:
      - ${MONGO_PORT1}:${MONGO_MACHINE_PORT}
    links:
      - mongo-1.mongo:mongo-1.mongo
      - mongo-2.mongo:mongo-2.mongo
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "octo_rs", "--journal", "--dbpath", "/data/db" ]
    networks:
      - acc

  libreoffice-server:
    image: libreoffice/online
    container_name: libreoffice-app
    expose:
      - 9980
    ports:
      - "9980:9980"
    environment:
      - username=admin
      - password=adminadmin
    restart: always

  approval-server:
    container_name: octonius_approval-server
    image: ${DOCKER_USER}/${DOCKER_REPO}:approval-server
    ports:
      - ${APPROVAL_SERVER_PORT}:${MACHINE_PORT}
    restart: always
    volumes:
      - ${VOLUME_NODE_MODULES}
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${MACHINE_PORT}
      - HOST=${HOST}
      - JWT_KEY=${JWT_KEY}
      - DB_URL=${DB_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - HEADER_EXTERNAL_KEY=${HEADER_EXTERNAL_KEY}
      - PROTOCOL=${PROTOCOL}
      - DOMAIN=${DOMAIN}
      - MANAGEMENT_URL=${MANAGEMENT_URL}
      - PROXY_AVAILABLE=${PROXY_AVAILABLE}
      - PROXY_PROTOCOL=${PROXY_PROTOCOL}
      - PROXY_HOST=${PROXY_HOST}
      - PROXY_PORT=${PROXY_PORT}
    depends_on:
      - mongo-0.mongo
      - mongo-1.mongo
      - mongo-2.mongo
    links:
      - mongo-0.mongo
      - mongo-1.mongo
      - mongo-2.mongo
    networks:
      - acc

  auths-server:
    container_name: octonius_auths-server
    image: ${DOCKER_USER}/${DOCKER_REPO}:auths-server
    ports:
      - ${AUTHS_SERVER_PORT}:${MACHINE_PORT}
    restart: always
    volumes:
      - ${VOLUME_NODE_MODULES}
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${MACHINE_PORT}
      - HOST=${HOST}
      - JWT_KEY=${JWT_KEY}
      - DB_URL=${DB_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - HEADER_EXTERNAL_KEY=${HEADER_EXTERNAL_KEY}
      - PROTOCOL=${PROTOCOL}
      - DOMAIN=${DOMAIN}
      - MANAGEMENT_URL=${MANAGEMENT_URL}
      - PROXY_AVAILABLE=${PROXY_AVAILABLE}
      - PROXY_PROTOCOL=${PROXY_PROTOCOL}
      - PROXY_HOST=${PROXY_HOST}
      - PROXY_PORT=${PROXY_PORT}
    depends_on:
      - mongo-0.mongo
      - mongo-1.mongo
      - mongo-2.mongo
    links:
      - mongo-0.mongo
      - mongo-1.mongo
      - mongo-2.mongo
    networks:
      - acc
             
  groups-server:
    container_name: octonius_groups-server
    image: ${DOCKER_USER}/${DOCKER_REPO}:groups-server
    ports:
      - ${GROUPS_SERVER_PORT}:${MACHINE_PORT}
    restart: always
    volumes:
      - ${VOLUME_NODE_MODULES}
      - acc_groups_uploads_data:${VOLUME_UPLOADS}
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${MACHINE_PORT}
      - HOST=${HOST}
      - JWT_KEY=${JWT_KEY}
      - DB_URL=${DB_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - HEADER_EXTERNAL_KEY=${HEADER_EXTERNAL_KEY}
      - PROTOCOL=${PROTOCOL}
      - DOMAIN=${DOMAIN}
      - MANAGEMENT_URL=${MANAGEMENT_URL}
      - PROXY_AVAILABLE=${PROXY_AVAILABLE}
      - PROXY_PROTOCOL=${PROXY_PROTOCOL}
      - PROXY_HOST=${PROXY_HOST}
      - PROXY_PORT=${PROXY_PORT}
    depends_on:
      - mongo-0.mongo
      - mongo-1.mongo
      - mongo-2.mongo
    links:
      - mongo-0.mongo
      - mongo-1.mongo
      - mongo-2.mongo
    networks:
      - acc
         
  workspaces-server:
    container_name: octonius_workspaces-server
    image: ${DOCKER_USER}/${DOCKER_REPO}:workspaces-server
    ports:
      - ${WORKSPACES_SERVER_PORT}:${MACHINE_PORT}
    restart: always
    volumes:
      - ${VOLUME_NODE_MODULES}
      - acc_workspaces_uploads_data:/usr/app/uploads
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${MACHINE_PORT}
      - HOST=${HOST}
      - JWT_KEY=${JWT_KEY}
      - DB_URL=${DB_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - HEADER_EXTERNAL_KEY=${HEADER_EXTERNAL_KEY}
      - PROTOCOL=${PROTOCOL}
      - DOMAIN=${DOMAIN}
      - MANAGEMENT_URL=${MANAGEMENT_URL}
      - PROXY_AVAILABLE=${PROXY_AVAILABLE}
      - PROXY_PROTOCOL=${PROXY_PROTOCOL}
      - PROXY_HOST=${PROXY_HOST}
      - PROXY_PORT=${PROXY_PORT}
    depends_on:
      - mongo-0.mongo
      - mongo-1.mongo
      - mongo-2.mongo
    links:
      - mongo-0.mongo
      - mongo-1.mongo
      - mongo-2.mongo
    networks:
      - acc
    
  users-server:
    container_name: octonius_users-server
    image: ${DOCKER_USER}/${DOCKER_REPO}:users-server
    ports:
      - ${USERS_SERVER_PORT}:${MACHINE_PORT}
    restart: always
    volumes:
      - ${VOLUME_NODE_MODULES}
      - acc_users_uploads_data:${VOLUME_UPLOADS}
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${MACHINE_PORT}
      - HOST=${HOST}
      - JWT_KEY=${JWT_KEY}
      - DB_URL=${DB_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - HEADER_EXTERNAL_KEY=${HEADER_EXTERNAL_KEY}
      - PROTOCOL=${PROTOCOL}
      - DOMAIN=${DOMAIN}
      - MANAGEMENT_URL=${MANAGEMENT_URL}
      - PROXY_AVAILABLE=${PROXY_AVAILABLE}
      - PROXY_PROTOCOL=${PROXY_PROTOCOL}
      - PROXY_HOST=${PROXY_HOST}
      - PROXY_PORT=${PROXY_PORT}
    depends_on:
      - mongo-0.mongo
      - mongo-1.mongo
      - mongo-2.mongo
    links:
      - mongo-0.mongo
      - mongo-1.mongo
      - mongo-2.mongo
    networks:
      - acc    
      
  posts-server:
    container_name: octonius_posts-server
    image: ${DOCKER_USER}/${DOCKER_REPO}:posts-server
    ports:
      - ${POSTS_SERVER_PORT}:${MACHINE_PORT}
    restart: always
    volumes:
      - ${VOLUME_NODE_MODULES}
      - acc_posts_uploads_data:${VOLUME_UPLOADS}
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${MACHINE_PORT}
      - HOST=${HOST}
      - JWT_KEY=${JWT_KEY}
      - DB_URL=${DB_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - HEADER_EXTERNAL_KEY=${HEADER_EXTERNAL_KEY}
      - PROTOCOL=${PROTOCOL}
      - DOMAIN=${DOMAIN}
      - MANAGEMENT_URL=${MANAGEMENT_URL}
      - PROXY_AVAILABLE=${PROXY_AVAILABLE}
      - PROXY_PROTOCOL=${PROXY_PROTOCOL}
      - PROXY_HOST=${PROXY_HOST}
      - PROXY_PORT=${PROXY_PORT}
    depends_on:
      - mongo-0.mongo
      - mongo-1.mongo
      - mongo-2.mongo
    links:
      - mongo-0.mongo
      - mongo-1.mongo
      - mongo-2.mongo
    networks:
      - acc
          
  notifications-server:
    container_name: octonius_notifications-server
    image: ${DOCKER_USER}/${DOCKER_REPO}:notifications-server
    ports:
      - ${NOTIFICATIONS_SERVER_PORT}:${MACHINE_PORT}
    restart: always
    volumes:
      - ${VOLUME_NODE_MODULES}
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${MACHINE_PORT}
      - HOST=${HOST}
      - JWT_KEY=${JWT_KEY}
      - DB_URL=${DB_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - HEADER_EXTERNAL_KEY=${HEADER_EXTERNAL_KEY}
      - PROTOCOL=${PROTOCOL}
      - DOMAIN=${DOMAIN}
      - MANAGEMENT_URL=${MANAGEMENT_URL}
      - PROXY_AVAILABLE=${PROXY_AVAILABLE}
      - PROXY_PROTOCOL=${PROXY_PROTOCOL}
      - PROXY_HOST=${PROXY_HOST}
      - PROXY_PORT=${PROXY_PORT}
    depends_on:
      - mongo-0.mongo
      - mongo-1.mongo
      - mongo-2.mongo
    links:
      - mongo-0.mongo
      - mongo-1.mongo
      - mongo-2.mongo
    networks:
      - acc
          
  utilities-server:
    container_name: octonius_utilities-server
    image: ${DOCKER_USER}/${DOCKER_REPO}:utilities-server
    ports:
      - ${UTILITIES_SERVER_PORT}:${MACHINE_PORT}
    restart: always
    volumes:
      - ${VOLUME_NODE_MODULES}
      - acc_utilities_uploads_data:${VOLUME_UPLOADS}
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${MACHINE_PORT}
      - HOST=${HOST}
      - JWT_KEY=${JWT_KEY}
      - DB_URL=${DB_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - HEADER_EXTERNAL_KEY=${HEADER_EXTERNAL_KEY}
      - PROTOCOL=${PROTOCOL}
      - DOMAIN=${DOMAIN}
      - MANAGEMENT_URL=${MANAGEMENT_URL}
      - PROXY_AVAILABLE=${PROXY_AVAILABLE}
      - PROXY_PROTOCOL=${PROXY_PROTOCOL}
      - PROXY_HOST=${PROXY_HOST}
      - PROXY_PORT=${PROXY_PORT}
    depends_on:
      - mongo-0.mongo
      - mongo-1.mongo
      - mongo-2.mongo
    links:
      - mongo-0.mongo
      - mongo-1.mongo
      - mongo-2.mongo
    networks:
      - acc
    
  folio-server:
    container_name: octonius_folio-server
    image: ${DOCKER_USER}/${DOCKER_REPO}:folio-server
    ports:
      - ${FOLIO_SERVER_PORT}:${MACHINE_PORT}
    restart: always
    volumes:
      - ${VOLUME_NODE_MODULES}
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${MACHINE_PORT}
      - HOST=${HOST}
      - JWT_KEY=${JWT_KEY}
      - DB_URL=${DB_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - HEADER_EXTERNAL_KEY=${HEADER_EXTERNAL_KEY}
      - PROTOCOL=${PROTOCOL}
      - DOMAIN=${DOMAIN}
      - MANAGEMENT_URL=${MANAGEMENT_URL}
      - PROXY_AVAILABLE=${PROXY_AVAILABLE}
      - PROXY_PROTOCOL=${PROXY_PROTOCOL}
      - PROXY_HOST=${PROXY_HOST}
      - PROXY_PORT=${PROXY_PORT}
    depends_on:
      - mongo-0.mongo
      - mongo-1.mongo
      - mongo-2.mongo
    links:
      - mongo-0.mongo
      - mongo-1.mongo
      - mongo-2.mongo
    networks:
      - acc
    
  search-server:
    container_name: octonius_search-server
    image: ${DOCKER_USER}/${DOCKER_REPO}:search-server
    ports:
      - ${SEARCH_SERVER_PORT}:${MACHINE_PORT}
    restart: always
    volumes:
      - ${VOLUME_NODE_MODULES}
      - acc_search_uploads_data:${VOLUME_UPLOADS}
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${MACHINE_PORT}
      - HOST=${HOST}
      - JWT_KEY=${JWT_KEY}
      - DB_URL=${DB_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - HEADER_EXTERNAL_KEY=${HEADER_EXTERNAL_KEY}
      - PROTOCOL=${PROTOCOL}
      - DOMAIN=${DOMAIN}
      - MANAGEMENT_URL=${MANAGEMENT_URL}
      - PROXY_AVAILABLE=${PROXY_AVAILABLE}
      - PROXY_PROTOCOL=${PROXY_PROTOCOL}
      - PROXY_HOST=${PROXY_HOST}
      - PROXY_PORT=${PROXY_PORT}
    depends_on:
      - mongo-0.mongo
      - mongo-1.mongo
      - mongo-2.mongo
    links:
      - mongo-0.mongo
      - mongo-1.mongo
      - mongo-2.mongo
    networks:
      - acc

  integrations-server:
    container_name: octonius_integrations-server
    image: ${DOCKER_USER}/${DOCKER_REPO}:integrations-server
    ports:
      - ${INTEGRATIONS_SERVER_PORT}:${MACHINE_PORT}
    restart: always
    volumes:
      - ${VOLUME_NODE_MODULES}
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${MACHINE_PORT}
      - HOST=${HOST}
      - JWT_KEY=${JWT_KEY}
      - DB_URL=${DB_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - HEADER_EXTERNAL_KEY=${HEADER_EXTERNAL_KEY}
      - PROTOCOL=${PROTOCOL}
      - DOMAIN=${DOMAIN}
      - TEAMS_BOT_URL=${TEAMS_BOT_URL}
      - SLACK_CLIENT_ID=${SLACK_CLIENT_ID}
      - SLACK_CLIENT_SECRET=${SLACK_CLIENT_SECRET}
      - SLACK_BOT_ACCESS_TOKEN=${SLACK_BOT_ACCESS_TOKEN}
      - MANAGEMENT_URL=${MANAGEMENT_URL}
      - PROXY_AVAILABLE=${PROXY_AVAILABLE}
      - PROXY_PROTOCOL=${PROXY_PROTOCOL}
      - PROXY_HOST=${PROXY_HOST}
      - PROXY_PORT=${PROXY_PORT}
    depends_on:
      - mongo-0.mongo
      - mongo-1.mongo
      - mongo-2.mongo
    links:
      - mongo-0.mongo
      - mongo-1.mongo
      - mongo-2.mongo
    networks:
      - acc
      
  flamingo-server:
    container_name: octonius_flamingo-server
    image: ${DOCKER_USER}/${DOCKER_REPO}:flamingo-server
    ports:
      - ${FLAMINGO_SERVER_PORT}:${MACHINE_PORT}
    restart: always
    volumes:
      - ${VOLUME_NODE_MODULES}
      - acc_flamingo_uploads_data:${VOLUME_UPLOADS}
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${MACHINE_PORT}
      - HOST=${HOST}
      - JWT_KEY=${JWT_KEY}
      - DB_URL=${DB_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - HEADER_EXTERNAL_KEY=${HEADER_EXTERNAL_KEY}
      - PROTOCOL=${PROTOCOL}
      - DOMAIN=${DOMAIN}
      - MANAGEMENT_URL=${MANAGEMENT_URL}
      - PROXY_AVAILABLE=${PROXY_AVAILABLE}
      - PROXY_PROTOCOL=${PROXY_PROTOCOL}
      - PROXY_HOST=${PROXY_HOST}
      - PROXY_PORT=${PROXY_PORT}
    depends_on:
      - mongo-0.mongo
      - mongo-1.mongo
      - mongo-2.mongo
    links:
      - mongo-0.mongo
      - mongo-1.mongo
      - mongo-2.mongo
    networks:
      - acc

  client:
    container_name: octonius_client
    image: ${DOCKER_USER}/${DOCKER_REPO}:client
    volumes:
      - ${VOLUME_NODE_MODULES}
    environment: 
      - PROTOCOL=${PROTOCOL}
      - DOMAIN=${DOMAIN}
      - WEBSOCKET=${WEBSOCKET}
      - mgmt_portal_domain=${mgmt_portal_domain}
      - SLACK_CLIENT_ID=${SLACK_CLIENT_ID}
    depends_on:
      - mongo-0.mongo
      - mongo-1.mongo
      - mongo-2.mongo
      - approval-server
      - auths-server
      - groups-server
      - workspaces-server
      - users-server
      - posts-server
      - notifications-server
      - utilities-server
      - folio-server
      - search-server
      - flamingo-server
    networks:
      - acc
    
  nginx:
    container_name: octonius_nginx
    image: ${DOCKER_USER}/${DOCKER_REPO}:nginx
    restart: always
    ports:
      - ${APPLICATION_PORT}:${NGINX_PORT}
    depends_on:
      - mongo-0.mongo
      - mongo-1.mongo
      - mongo-2.mongo
      - approval-server
      - auths-server
      - groups-server
      - workspaces-server
      - users-server
      - posts-server
      - notifications-server
      - utilities-server
      - folio-server
      - search-server
      - flamingo-server
      - client
    networks:
      - acc
    
volumes:
  #acc_db_data:
  #  driver: local
  #  driver_opts:
  #    type: none
  #    device: ${PWD}/data/db
  #    o: bind

  acc_groups_uploads_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/uploads/groups
      o: bind
  
  acc_posts_uploads_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/uploads/posts
      o: bind

  acc_users_uploads_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/uploads/users
      o: bind

  acc_workspaces_uploads_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/uploads/workspaces
      o: bind

  acc_utilities_uploads_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/uploads/utilities
      o: bind

  acc_flamingo_uploads_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/uploads/flamingo
      o: bind

  acc_search_uploads_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/uploads/search
      o: bind
        
networks:
  acc: 
    driver: bridge
