version: "3.3"

services:

  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - production_db_data:/data/db
    ports:
      - 27017:27017
    networks:
      - productionapp
    
      
  mailing-server:
    image: octoniusapp/octonius-prod:mailing-server
    ports:
      - 2000:2000
    restart: always
    volumes:
      - /usr/app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=2000
      - HOST=0.0.0.0
      - JWT_KEY=asfsaf12safas23fsafa12sf
      - DB_URL=mongodb://mongodb:27017/octonius
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENDGRID_KEY=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
      - SK_STRIPE=sk_live_WupyMoQf93S59gwTqmYpmWel
      - STRIPE_PLAN=plan_EK1rDLfKr9NRkU
      - WEBHOOK_PS_SECRET=whsec_pmcLdxoYxBAdZswT2ZzWYep2WmnBW8Sn
      - HEADER_EXTERNAL_KEY=HEADERIDSHAREDFOROCTONIUS
      - PROTOCOL=https
      - DOMAIN=app.octonius.com
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - productionapp
    
      
  auths-server:
    image: octoniusapp/octonius-prod:auths-server
    ports:
      - 3000:3000
    restart: always
    volumes:
      - /usr/app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      - JWT_KEY=asfsaf12safas23fsafa12sf
      - DB_URL=mongodb://mongodb:27017/octonius
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENDGRID_KEY=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
      - SK_STRIPE=sk_live_WupyMoQf93S59gwTqmYpmWel
      - STRIPE_PLAN=plan_EK1rDLfKr9NRkU
      - WEBHOOK_PS_SECRET=whsec_pmcLdxoYxBAdZswT2ZzWYep2WmnBW8Sn
      - HEADER_EXTERNAL_KEY=HEADERIDSHAREDFOROCTONIUS
      - PROTOCOL=https
      - DOMAIN=app.octonius.com
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - productionapp
    
         
  groups-server:
    image: octoniusapp/octonius-prod:groups-server
    ports:
      - 4000:4000
    restart: always
    volumes:
      - /usr/app/node_modules
      - production_groups_uploads_data:/usr/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=4000
      - HOST=0.0.0.0
      - JWT_KEY=asfsaf12safas23fsafa12sf
      - DB_URL=mongodb://mongodb:27017/octonius
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENDGRID_KEY=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
      - SK_STRIPE=sk_live_WupyMoQf93S59gwTqmYpmWel
      - STRIPE_PLAN=plan_EK1rDLfKr9NRkU
      - WEBHOOK_PS_SECRET=whsec_pmcLdxoYxBAdZswT2ZzWYep2WmnBW8Sn
      - HEADER_EXTERNAL_KEY=HEADERIDSHAREDFOROCTONIUS
      - PROTOCOL=https
      - DOMAIN=app.octonius.com
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - productionapp
    
      
  workspaces-server:
    image: octoniusapp/octonius-prod:workspaces-server
    ports:
      - 5000:5000
    restart: always
    volumes:
      - /usr/app/node_modules
      - production_workspaces_uploads_data:/usr/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=5000
      - HOST=0.0.0.0
      - JWT_KEY=asfsaf12safas23fsafa12sf
      - DB_URL=mongodb://mongodb:27017/octonius
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENDGRID_KEY=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
      - SK_STRIPE=sk_live_WupyMoQf93S59gwTqmYpmWel
      - STRIPE_PLAN=plan_EK1rDLfKr9NRkU
      - WEBHOOK_PS_SECRET=whsec_pmcLdxoYxBAdZswT2ZzWYep2WmnBW8Sn
      - HEADER_EXTERNAL_KEY=HEADERIDSHAREDFOROCTONIUS
      - PROTOCOL=https
      - DOMAIN=app.octonius.com
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - productionapp
    
      
  search-server:
    container_name: search-server
    image: octoniusapp/octonius-prod:search-server
    ports:
      - 12000:12000
    restart: always
    volumes:
      - /usr/app/node_modules
      - production_search_uploads_data:/usr/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=12000
      - HOST=0.0.0.0
      - JWT_KEY=asfsaf12safas23fsafa12sf
      - DB_URL=mongodb://mongodb:27017/octonius
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENDGRID_KEY=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
      - SK_STRIPE=sk_live_WupyMoQf93S59gwTqmYpmWel
      - STRIPE_PLAN=plan_EK1rDLfKr9NRkU
      - WEBHOOK_PS_SECRET=whsec_pmcLdxoYxBAdZswT2ZzWYep2WmnBW8Sn
      - HEADER_EXTERNAL_KEY=HEADERIDSHAREDFOROCTONIUS
      - PROTOCOL=https
      - DOMAIN=app.octonius.com
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - productionapp
    
      
  users-server:
    container_name: users-server
    image: octoniusapp/octonius-prod:users-server
    ports:
      - 7000:7000
    restart: always
    volumes:
      - /usr/app/node_modules
      - production_users_uploads_data:/usr/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=7000
      - HOST=0.0.0.0
      - JWT_KEY=asfsaf12safas23fsafa12sf
      - DB_URL=mongodb://mongodb:27017/octonius
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENDGRID_KEY=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
      - SK_STRIPE=sk_live_WupyMoQf93S59gwTqmYpmWel
      - STRIPE_PLAN=plan_EK1rDLfKr9NRkU
      - WEBHOOK_PS_SECRET=whsec_pmcLdxoYxBAdZswT2ZzWYep2WmnBW8Sn
      - HEADER_EXTERNAL_KEY=HEADERIDSHAREDFOROCTONIUS
      - PROTOCOL=https
      - DOMAIN=app.octonius.com
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - productionapp
    
      
  posts-server:
    container_name: posts-server
    image: octoniusapp/octonius-prod:posts-server
    ports:
      - 8000:8000
    restart: always
    volumes:
      - /usr/app/node_modules
      - production_posts_uploads_data:/usr/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=8000
      - HOST=0.0.0.0
      - JWT_KEY=asfsaf12safas23fsafa12sf
      - DB_URL=mongodb://mongodb:27017/octonius
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENDGRID_KEY=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
      - SK_STRIPE=sk_live_WupyMoQf93S59gwTqmYpmWel
      - STRIPE_PLAN=plan_EK1rDLfKr9NRkU
      - WEBHOOK_PS_SECRET=whsec_pmcLdxoYxBAdZswT2ZzWYep2WmnBW8Sn
      - HEADER_EXTERNAL_KEY=HEADERIDSHAREDFOROCTONIUS
      - PROTOCOL=https
      - DOMAIN=app.octonius.com
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - productionapp
    
      
  notifications-server:
    container_name: notifications-server
    image: octoniusapp/octonius-prod:notifications-server
    ports:
      - 9000:9000
    restart: always
    volumes:
      - /usr/app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=9000
      - HOST=0.0.0.0
      - JWT_KEY=asfsaf12safas23fsafa12sf
      - DB_URL=mongodb://mongodb:27017/octonius
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENDGRID_KEY=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
      - SK_STRIPE=sk_live_WupyMoQf93S59gwTqmYpmWel
      - STRIPE_PLAN=plan_EK1rDLfKr9NRkU
      - WEBHOOK_PS_SECRET=whsec_pmcLdxoYxBAdZswT2ZzWYep2WmnBW8Sn
      - HEADER_EXTERNAL_KEY=HEADERIDSHAREDFOROCTONIUS
      - PROTOCOL=https
      - DOMAIN=app.octonius.com
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - productionapp
    
      
  utilities-server:
    container_name: utilities-server
    image: octoniusapp/octonius-prod:utilities-server
    ports:
      - 10000:10000
    restart: always
    volumes:
      - /usr/app/node_modules
      - production_utilities_uploads_data:/usr/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=10000
      - HOST=0.0.0.0
      - JWT_KEY=asfsaf12safas23fsafa12sf
      - DB_URL=mongodb://mongodb:27017/octonius
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENDGRID_KEY=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
      - SK_STRIPE=sk_live_WupyMoQf93S59gwTqmYpmWel
      - STRIPE_PLAN=plan_EK1rDLfKr9NRkU
      - WEBHOOK_PS_SECRET=whsec_pmcLdxoYxBAdZswT2ZzWYep2WmnBW8Sn
      - HEADER_EXTERNAL_KEY=HEADERIDSHAREDFOROCTONIUS
      - PROTOCOL=https
      - DOMAIN=app.octonius.com
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - productionapp
    

  folio-server:
    container_name: folio-server
    image: octoniusapp/octonius-prod:folio-server
    ports:
      - 11000:11000
    restart: always
    volumes:
      - /usr/app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=11000
      - HOST=0.0.0.0
      - JWT_KEY=asfsaf12safas23fsafa12sf
      - DB_URL=mongodb://mongodb:27017/octonius
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENDGRID_KEY=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
      - SK_STRIPE=sk_live_WupyMoQf93S59gwTqmYpmWel
      - STRIPE_PLAN=plan_EK1rDLfKr9NRkU
      - WEBHOOK_PS_SECRET=whsec_pmcLdxoYxBAdZswT2ZzWYep2WmnBW8Sn
      - HEADER_EXTERNAL_KEY=HEADERIDSHAREDFOROCTONIUS
      - PROTOCOL=https
      - DOMAIN=app.octonius.com
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - productionapp
    

  integrations-server:
    container_name: integrations-server
    image: octoniusapp/octonius-prod:integrations-server
    ports:
      - 13000:13000
    restart: always
    volumes:
      - /usr/app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=13000
      - HOST=0.0.0.0
      - JWT_KEY=asfsaf12safas23fsafa12sf
      - DB_URL=mongodb://mongodb:27017/octonius
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENDGRID_KEY=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
      - SK_STRIPE=sk_live_WupyMoQf93S59gwTqmYpmWel
      - STRIPE_PLAN=plan_EK1rDLfKr9NRkU
      - WEBHOOK_PS_SECRET=whsec_pmcLdxoYxBAdZswT2ZzWYep2WmnBW8Sn
      - HEADER_EXTERNAL_KEY=HEADERIDSHAREDFOROCTONIUS
      - PROTOCOL=https
      - DOMAIN=app.octonius.com
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - productionapp
    
      
  client:
    container_name: client
    image: octoniusapp/octonius-prod:client
    volumes:
      - /usr/app/node_modules
    depends_on:
      - mongodb
      - mailing-server
      - auths-server
      - groups-server
      - workspaces-server
      - users-server
      - posts-server
      - notifications-server
      - utilities-server
      - folio-server
      - search-server
    networks:
      - productionapp
    

  nginx:
    container_name: nginx
    image: octoniusapp/octonius-prod:nginx
    restart: always
    ports:
      - 8080:80
    depends_on:
      - mongodb
      - mailing-server
      - auths-server
      - groups-server
      - workspaces-server
      - users-server
      - posts-server
      - notifications-server
      - utilities-server
      - folio-server
      - search-server
      - client
    networks:
      - productionapp
    

volumes:
  production_db_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/db
      o: bind

  production_groups_uploads_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/uploads/groups
      o: bind
  
  production_posts_uploads_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/uploads/posts
      o: bind

  production_users_uploads_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/uploads/users
      o: bind

  production_workspaces_uploads_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/uploads/workspaces
      o: bind

  production_utilities_uploads_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/uploads/utilities
      o: bind

  production_search_uploads_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/uploads/search
      o: bind
  
      
networks:
  productionapp: 
    driver: bridge
